#!/usr/bin/env python3
"""
flow_rate_calibration.py

Generate G-code for calibrating extruder flow rate (extrusion multiplier).
Creates test patterns with varying flow rates to find optimal settings.

Usage:
    python tools/flow_rate_calibration.py --filament PLA
    python tools/flow_rate_calibration.py --filament PETG --output flow_test.gcode
    python tools/flow_rate_calibration.py --min-flow 90 --max-flow 110 --step 2
    python tools/flow_rate_calibration.py --method single-wall
"""

import argparse
import json
import sys
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional


class CalibrationMethod(Enum):
    SINGLE_WALL = "single-wall"
    CUBE = "cube"
    HOLLOW = "hollow"


@dataclass
class FilamentFlowSettings:
    name: str
    default_flow: float
    flow_range: tuple
    nozzle_temp: float
    bed_temp: float
    fan_speed: int
    notes: str


FILAMENT_FLOW_CONFIGS = {
    "PLA": FilamentFlowSettings(
        name="PLA",
        default_flow=100.0,
        flow_range=(90, 110),
        nozzle_temp=210.0,
        bed_temp=60.0,
        fan_speed=100,
        notes="PLA typically needs accurate flow. Check for gaps or over-extrusion."
    ),
    "PETG": FilamentFlowSettings(
        name="PETG",
        default_flow=100.0,
        flow_range=(95, 110),
        nozzle_temp=240.0,
        bed_temp=80.0,
        fan_speed=50,
        notes="PETG often benefits from slight over-extrusion for better layer bonding."
    ),
    "ABS": FilamentFlowSettings(
        name="ABS",
        default_flow=100.0,
        flow_range=(95, 105),
        nozzle_temp=250.0,
        bed_temp=100.0,
        fan_speed=0,
        notes="ABS benefits from enclosure. Watch for layer separation."
    ),
    "ASA": FilamentFlowSettings(
        name="ASA",
        default_flow=100.0,
        flow_range=(95, 105),
        nozzle_temp=255.0,
        bed_temp=100.0,
        fan_speed=20,
        notes="Similar to ABS but better UV resistance. Needs enclosure."
    ),
    "TPU": FilamentFlowSettings(
        name="TPU",
        default_flow=100.0,
        flow_range=(95, 105),
        nozzle_temp=220.0,
        bed_temp=50.0,
        fan_speed=80,
        notes="TPU needs slower speeds. Direct drive recommended."
    ),
    "NYLON": FilamentFlowSettings(
        name="Nylon",
        default_flow=100.0,
        flow_range=(95, 110),
        nozzle_temp=260.0,
        bed_temp=90.0,
        fan_speed=30,
        notes="Nylon must be dry. Needs enclosure for best results."
    ),
    "PC": FilamentFlowSettings(
        name="Polycarbonate",
        default_flow=100.0,
        flow_range=(95, 110),
        nozzle_temp=280.0,
        bed_temp=110.0,
        fan_speed=0,
        notes="High temp material. Requires all-metal hotend."
    ),
    "PP": FilamentFlowSettings(
        name="Polypropylene",
        default_flow=100.0,
        flow_range=(90, 110),
        nozzle_temp=240.0,
        bed_temp=100.0,
        fan_speed=50,
        notes="PP is tricky. Use adhesive on bed surface."
    ),
    "PVA": FilamentFlowSettings(
        name="PVA",
        default_flow=100.0,
        flow_range=(95, 105),
        nozzle_temp=215.0,
        bed_temp=50.0,
        fan_speed=100,
        notes="Support material. Keep dry - absorbs moisture rapidly."
    )
}


@dataclass
class FlowTestConfig:
    min_flow: float
    max_flow: float
    flow_step: float
    test_size: float
    layer_height: float
    nozzle_diameter: float
    wall_line_count: int
    print_speed: int
    first_layer_speed: int
    base_x: float
    base_y: float


DEFAULT_CONFIG = FlowTestConfig(
    min_flow=90.0,
    max_flow=110.0,
    flow_step=2.0,
    test_size=20.0,
    layer_height=0.2,
    nozzle_diameter=0.4,
    wall_line_count=2,
    print_speed=60,
    first_layer_speed=20,
    base_x=30.0,
    base_y=30.0
)


def generate_start_gcode(
    bed_temp: float,
    nozzle_temp: float,
    fan_speed: int,
    layer_height: float,
    nozzle_diameter: float
) -> str:
    lines = [
        "; Flow Rate Calibration G-code",
        "; Generated by OpenPrint3D flow_rate_calibration.py",
        "; ========================================",
        ";",
        "; This test prints patterns at varying flow rates",
        "; to find the optimal extrusion multiplier.",
        ";",
        "; Method: Print test cubes/walls, measure actual",
        "; dimensions vs expected dimensions.",
        ";",
        "; Calculation:",
        ";   Flow % = (Target Width / Actual Width) × Current Flow %",
        ";",
        "; ========================================",
        "",
        "G90 ; Absolute positioning",
        "M82 ; Absolute extrusion mode",
        "",
        "; Home all axes",
        "G28 ; Home all axes",
        "",
        "; Set temperatures",
        f"M140 S{bed_temp:.0f} ; Set bed temperature",
        f"M190 S{bed_temp:.0f} ; Wait for bed temperature",
        f"M104 S{nozzle_temp:.0f} ; Set nozzle temperature",
        f"M109 S{nozzle_temp:.0f} ; Wait for nozzle temperature",
        "",
        "; Prime line",
        "G1 Z5 F3000 ; Lift nozzle",
        "G1 X10 Y10 F6000 ; Move to start position",
        "G1 Z{:.2f} F3000 ; Lower to first layer height".format(layer_height),
        "G1 X200 E25 F1500 ; Prime line",
        "G1 Z2 F3000 ; Lift nozzle",
        "G1 X10 F6000 ; Move away",
        "",
        f"M106 S{int(fan_speed * 255 / 100)} ; Set fan to {fan_speed}%",
        "",
        "G92 E0 ; Reset extruder position",
        "",
    ]
    return "\n".join(lines)


def generate_flow_test_cube(
    flow_rate: float,
    test_num: int,
    start_x: float,
    start_y: float,
    config: FlowTestConfig,
    layers: int = 5
) -> str:
    lines = [
        "",
        f"; ========================================",
        f"; FLOW TEST {test_num}: {flow_rate:.0f}%",
        f"; ========================================",
        f"M221 S{flow_rate:.0f} ; Set flow rate to {flow_rate:.0f}%",
        "",
    ]
    
    size = config.test_size
    e_pos = 0.0
    
    perimeter = 4 * size
    wall_width = config.nozzle_diameter
    
    for layer in range(layers):
        z = (layer + 1) * config.layer_height
        speed = config.first_layer_speed if layer == 0 else config.print_speed
        
        lines.append(f"; Layer {layer + 1}/{layers}")
        lines.append(f"G1 Z{z:.2f} F3000")
        lines.append(f"G1 X{start_x:.2f} Y{start_y:.2f} F6000")
        
        for wall in range(config.wall_line_count):
            offset = wall * wall_width
            
            extrusion_per_side = size * config.layer_height * wall_width / (wall_width * config.layer_height)
            
            lines.append(f"G1 X{start_x + size - offset:.2f} Y{start_y + offset:.2f} E{e_pos + extrusion_per_side:.3f} F{speed * 60}")
            e_pos += extrusion_per_side
            lines.append(f"G1 X{start_x + size - offset:.2f} Y{start_y + size - offset:.2f} E{e_pos + extrusion_per_side:.3f}")
            e_pos += extrusion_per_side
            lines.append(f"G1 X{start_x + offset:.2f} Y{start_y + size - offset:.2f} E{e_pos + extrusion_per_side:.3f}")
            e_pos += extrusion_per_side
            lines.append(f"G1 X{start_x + offset:.2f} Y{start_y + offset:.2f} E{e_pos + extrusion_per_side:.3f}")
            e_pos += extrusion_per_side
        
        lines.append("")
    
    lines.append(f"M221 S100 ; Reset flow to 100%")
    lines.append("")
    
    return "\n".join(lines)


def generate_single_wall_test(
    flow_rate: float,
    test_num: int,
    start_x: float,
    start_y: float,
    config: FlowTestConfig,
    layers: int = 10
) -> str:
    lines = [
        "",
        f"; ========================================",
        f"; SINGLE WALL TEST {test_num}: {flow_rate:.0f}%",
        f"; ========================================",
        f"M221 S{flow_rate:.0f} ; Set flow rate to {flow_rate:.0f}%",
        "",
        f"; Wall length: {config.test_size:.0f}mm",
        f"; Expected wall width: {config.nozzle_diameter:.2f}mm",
        "",
    ]
    
    e_pos = 0.0
    
    for layer in range(layers):
        z = (layer + 1) * config.layer_height
        speed = config.first_layer_speed if layer == 0 else config.print_speed
        
        lines.append(f"; Layer {layer + 1}/{layers}")
        lines.append(f"G1 Z{z:.2f} F3000")
        lines.append(f"G1 X{start_x:.2f} Y{start_y:.2f} F6000")
        
        extrusion = config.test_size * config.layer_height * config.nozzle_diameter / (config.nozzle_diameter * config.layer_height)
        
        lines.append(f"G1 X{start_x + config.test_size:.2f} Y{start_y:.2f} E{e_pos + extrusion:.3f} F{speed * 60}")
        e_pos += extrusion
        
        lines.append(f"G1 X{start_x:.2f} Y{start_y + 2:.2f} F6000")
        lines.append(f"G1 X{start_x + config.test_size:.2f} Y{start_y + 2:.2f} E{e_pos + extrusion:.3f} F{speed * 60}")
        e_pos += extrusion
        
        lines.append("")
    
    lines.append(f"M221 S100 ; Reset flow to 100%")
    lines.append("")
    
    return "\n".join(lines)


def generate_hollow_cube_test(
    flow_rate: float,
    test_num: int,
    start_x: float,
    start_y: float,
    config: FlowTestConfig,
    layers: int = 10
) -> str:
    lines = [
        "",
        f"; ========================================",
        f"; HOLLOW CUBE TEST {test_num}: {flow_rate:.0f}%",
        f"; ========================================",
        f"M221 S{flow_rate:.0f} ; Set flow rate to {flow_rate:.0f}%",
        "",
        f"; Cube size: {config.test_size:.0f}mm (single wall)",
        f"; Measure wall thickness with calipers",
        "",
    ]
    
    size = config.test_size
    e_pos = 0.0
    
    for layer in range(layers):
        z = (layer + 1) * config.layer_height
        speed = config.first_layer_speed if layer == 0 else config.print_speed
        
        lines.append(f"; Layer {layer + 1}/{layers}")
        lines.append(f"G1 Z{z:.2f} F3000")
        lines.append(f"G1 X{start_x:.2f} Y{start_y:.2f} F6000")
        
        extrusion_per_side = size * config.layer_height / config.nozzle_diameter
        
        lines.append(f"G1 X{start_x + size:.2f} Y{start_y:.2f} E{e_pos + extrusion_per_side:.3f} F{speed * 60}")
        e_pos += extrusion_per_side
        lines.append(f"G1 X{start_x + size:.2f} Y{start_y + size:.2f} E{e_pos + extrusion_per_side:.3f}")
        e_pos += extrusion_per_side
        lines.append(f"G1 X{start_x:.2f} Y{start_y + size:.2f} E{e_pos + extrusion_per_side:.3f}")
        e_pos += extrusion_per_side
        lines.append(f"G1 X{start_x:.2f} Y{start_y:.2f} E{e_pos + extrusion_per_side:.3f}")
        e_pos += extrusion_per_side
        
        lines.append("")
    
    lines.append(f"M221 S100 ; Reset flow to 100%")
    lines.append("")
    
    return "\n".join(lines)


def generate_end_gcode() -> str:
    lines = [
        "",
        "; ========================================",
        "; END G-CODE",
        "; ========================================",
        "",
        "M221 S100 ; Reset flow to 100%",
        "",
        "M104 S0 ; Turn off nozzle heater",
        "M140 S0 ; Turn off bed heater",
        "M106 S0 ; Turn off fan",
        "",
        "G1 Z50 F3000 ; Lift nozzle",
        "G1 X10 Y200 F6000 ; Park position",
        "",
        "M84 ; Disable motors",
        "",
        "; ========================================",
        "; FLOW CALIBRATION COMPLETE",
        "; ========================================",
        ";",
        "; How to analyze results:",
        ";",
        "; SINGLE WALL METHOD:",
        ";  1. Measure wall thickness with calipers",
        ";  2. Target = nozzle diameter (e.g., 0.4mm)",
        ";  3. Flow adjustment = (Target/Actual) × Current Flow",
        ";",
        "; HOLLOW CUBE METHOD:",
        ";  1. Measure external cube dimensions",
        ";  2. Expected = cube size + (wall thickness × 2)",
        ";  3. Wall thickness should = nozzle diameter",
        ";",
        "; CUBE METHOD (measuring infill):",
        ";  1. Measure cube dimensions",
        ";  2. Compare to expected size",
        ";  3. Adjust flow to achieve target dimensions",
        ";",
        "; Example calculation:",
        ";   Target wall: 0.40mm",
        ";   Measured wall: 0.44mm",
        ";   Correction: (0.40/0.44) × 100 = 90.9%",
        ";   New flow setting: ~91%",
        ";",
        "; Update your slicer flow/multiplier setting.",
        "; ========================================",
    ]
    return "\n".join(lines)


def generate_measurement_guide() -> str:
    lines = [
        "",
        "; ========================================",
        "; MEASUREMENT INSTRUCTIONS",
        "; ========================================",
        ";",
        "; Tools needed:",
        ";  - Digital calipers (0.01mm resolution)",
        ";  - Good lighting",
        ";",
        "; For single wall test:",
        ";  1. Measure wall at 3+ locations",
        ";  2. Average the measurements",
        ";  3. Compare to nozzle diameter",
        ";",
        "; For hollow cube test:",
        ";  1. Measure outer dimensions (X, Y)",
        ";  2. Subtract from expected size",
        ";  3. Divide by 2 for wall thickness",
        ";",
        "; Common issues:",
        ";  - Wall too thin = under-extrusion",
        ";  - Wall too thick = over-extrusion",
        ";  - Inconsistent = extruder issues",
        ";",
        "; ========================================",
    ]
    return "\n".join(lines)


def generate_flow_calibration(
    method: CalibrationMethod,
    filament_config: FilamentFlowSettings,
    config: FlowTestConfig,
    min_flow: Optional[float] = None,
    max_flow: Optional[float] = None,
    flow_step: Optional[float] = None
) -> str:
    min_f = min_flow if min_flow is not None else config.min_flow
    max_f = max_flow if max_flow is not None else config.max_flow
    step = flow_step if flow_step is not None else config.flow_step
    
    flow_rates = []
    current_flow = min_f
    while current_flow <= max_f + 0.01:
        flow_rates.append(round(current_flow, 1))
        current_flow += step
    
    if not flow_rates:
        print("[ERR] No flow rates generated. Check min/max/step values.", file=sys.stderr)
        sys.exit(1)
    
    gcode_parts = []
    
    gcode_parts.append(generate_start_gcode(
        bed_temp=filament_config.bed_temp,
        nozzle_temp=filament_config.nozzle_temp,
        fan_speed=filament_config.fan_speed,
        layer_height=config.layer_height,
        nozzle_diameter=config.nozzle_diameter
    ))
    
    gcode_parts.append("")
    gcode_parts.append("; Flow Calibration Configuration:")
    gcode_parts.append(f";   Filament: {filament_config.name}")
    gcode_parts.append(f";   Method: {method.value}")
    gcode_parts.append(f";   Flow range: {min_f:.0f}% - {max_f:.0f}%")
    gcode_parts.append(f";   Flow step: {step:.0f}%")
    gcode_parts.append(f";   Total tests: {len(flow_rates)}")
    gcode_parts.append(f";   Layer height: {config.layer_height}mm")
    gcode_parts.append(f";   Nozzle diameter: {config.nozzle_diameter}mm")
    gcode_parts.append(f";   Bed temperature: {filament_config.bed_temp:.0f}°C")
    gcode_parts.append(f";   Nozzle temperature: {filament_config.nozzle_temp:.0f}°C")
    gcode_parts.append(f";   Fan speed: {filament_config.fan_speed}%")
    gcode_parts.append(f";   Note: {filament_config.notes}")
    gcode_parts.append("")
    
    gcode_parts.append(generate_measurement_guide())
    
    test_spacing = config.test_size + 10
    
    for i, flow in enumerate(flow_rates):
        test_x = config.base_x + (i % 5) * test_spacing
        test_y = config.base_y + (i // 5) * (config.test_size + 15)
        
        if method == CalibrationMethod.SINGLE_WALL:
            gcode_parts.append(generate_single_wall_test(
                flow_rate=flow,
                test_num=i + 1,
                start_x=test_x,
                start_y=test_y,
                config=config
            ))
        elif method == CalibrationMethod.HOLLOW:
            gcode_parts.append(generate_hollow_cube_test(
                flow_rate=flow,
                test_num=i + 1,
                start_x=test_x,
                start_y=test_y,
                config=config
            ))
        else:
            gcode_parts.append(generate_flow_test_cube(
                flow_rate=flow,
                test_num=i + 1,
                start_x=test_x,
                start_y=test_y,
                config=config
            ))
    
    gcode_parts.append(generate_end_gcode())
    
    return "\n".join(gcode_parts)


def calculate_flow_adjustment(target_width: float, measured_width: float, current_flow: float = 100.0) -> dict:
    new_flow = (target_width / measured_width) * current_flow
    
    return {
        "target_width_mm": target_width,
        "measured_width_mm": measured_width,
        "current_flow_percent": current_flow,
        "calculated_flow_percent": round(new_flow, 1),
        "adjustment_percent": round(new_flow - current_flow, 1),
        "recommendation": f"Set flow to {round(new_flow, 1)}%"
    }


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate G-code for calibrating extruder flow rate."
    )
    parser.add_argument(
        "--filament", "-f",
        type=str,
        default="PLA",
        choices=list(FILAMENT_FLOW_CONFIGS.keys()),
        help="Filament type (default: PLA)"
    )
    parser.add_argument(
        "--method", "-m",
        type=str,
        choices=[m.value for m in CalibrationMethod],
        default=CalibrationMethod.SINGLE_WALL.value,
        help="Calibration method (default: single-wall)"
    )
    parser.add_argument(
        "--output", "-o",
        type=str,
        help="Output G-code file path (default: stdout)"
    )
    parser.add_argument(
        "--min-flow",
        type=float,
        help="Minimum flow rate percentage (default: 90)"
    )
    parser.add_argument(
        "--max-flow",
        type=float,
        help="Maximum flow rate percentage (default: 110)"
    )
    parser.add_argument(
        "--step",
        type=float,
        help="Flow rate step between tests (default: 2)"
    )
    parser.add_argument(
        "--layer-height",
        type=float,
        default=0.2,
        help="Layer height in mm (default: 0.2)"
    )
    parser.add_argument(
        "--nozzle-diameter",
        type=float,
        default=0.4,
        help="Nozzle diameter in mm (default: 0.4)"
    )
    parser.add_argument(
        "--size",
        type=float,
        default=20.0,
        help="Test cube/wall size in mm (default: 20)"
    )
    parser.add_argument(
        "--speed",
        type=int,
        default=60,
        help="Print speed in mm/s (default: 60)"
    )
    parser.add_argument(
        "--calculate",
        nargs=2,
        type=float,
        metavar=("TARGET", "MEASURED"),
        help="Calculate flow adjustment (target width, measured width)"
    )
    parser.add_argument(
        "--current-flow",
        type=float,
        default=100.0,
        help="Current flow rate for calculation (default: 100)"
    )
    
    args = parser.parse_args()
    
    if args.calculate:
        result = calculate_flow_adjustment(
            target_width=args.calculate[0],
            measured_width=args.calculate[1],
            current_flow=args.current_flow
        )
        print(json.dumps(result, indent=2))
        return
    
    try:
        method = CalibrationMethod(args.method.lower())
        filament_config = FILAMENT_FLOW_CONFIGS.get(args.filament.upper(), FILAMENT_FLOW_CONFIGS["PLA"])
    except ValueError:
        print(f"[ERR] Invalid method: {args.method}", file=sys.stderr)
        sys.exit(1)
    
    config = FlowTestConfig(
        min_flow=args.min_flow if args.min_flow else DEFAULT_CONFIG.min_flow,
        max_flow=args.max_flow if args.max_flow else DEFAULT_CONFIG.max_flow,
        flow_step=args.step if args.step else DEFAULT_CONFIG.flow_step,
        test_size=args.size,
        layer_height=args.layer_height,
        nozzle_diameter=args.nozzle_diameter,
        wall_line_count=DEFAULT_CONFIG.wall_line_count,
        print_speed=args.speed,
        first_layer_speed=DEFAULT_CONFIG.first_layer_speed,
        base_x=DEFAULT_CONFIG.base_x,
        base_y=DEFAULT_CONFIG.base_y
    )
    
    print(f"Generating flow calibration for: {filament_config.name}", file=sys.stderr)
    print(f"Method: {method.value}, Flow range: {config.min_flow:.0f}%-{config.max_flow:.0f}%", file=sys.stderr)
    
    gcode = generate_flow_calibration(
        method=method,
        filament_config=filament_config,
        config=config,
        min_flow=args.min_flow,
        max_flow=args.max_flow,
        flow_step=args.step
    )
    
    if args.output:
        with open(args.output, "w", encoding="utf-8") as f:
            f.write(gcode)
        print(f"G-code written to: {args.output}", file=sys.stderr)
    else:
        print(gcode)


if __name__ == "__main__":
    main()