#!/usr/bin/env python3
"""
pressure_advance_tuner.py

Generate G-code for calibrating Pressure Advance (PA) values.
Creates test patterns with varying PA values to find optimal settings.

Usage:
    python tools/pressure_advance_tuner.py --hotend direct
    python tools/pressure_advance_tuner.py --hotend bowden --output pa_test.gcode
    python tools/pressure_advance_tuner.py --hotend direct --min-pa 0.0 --max-pa 0.1 --step 0.01
    python tools/pressure_advance_tuner.py --hotend bowden --min-pa 0.0 --max-pa 1.0 --step 0.05
"""

import argparse
import sys
from dataclasses import dataclass
from enum import Enum
from typing import Optional


class HotendType(Enum):
    DIRECT = "direct"
    BOWDEN = "bowden"


@dataclass
class PASettings:
    min_pa: float
    max_pa: float
    step: float
    default_pa: float
    recommended_range: tuple
    description: str


HOTEND_PA_CONFIGS = {
    HotendType.DIRECT: PASettings(
        min_pa=0.0,
        max_pa=0.1,
        step=0.005,
        default_pa=0.04,
        recommended_range=(0.02, 0.06),
        description="Direct drive extruder - short filament path, low PA values typical"
    ),
    HotendType.BOWDEN: PASettings(
        min_pa=0.0,
        max_pa=1.0,
        step=0.02,
        default_pa=0.5,
        recommended_range=(0.3, 0.7),
        description="Bowden extruder - long filament path, higher PA values required"
    )
}


def generate_start_gcode(
    bed_temp: float,
    nozzle_temp: float,
    fan_speed: int,
    pressure_advance: float = 0.0,
    smooth_time: float = 0.040
) -> str:
    """Generate start G-code for PA calibration."""
    lines = [
        "; Pressure Advance Calibration G-code",
        "; Generated by OpenPrint3D pressure_advance_tuner.py",
        "; ========================================",
        ";",
        "; This test prints lines at varying PA values",
        "; to help find optimal pressure advance setting.",
        ";",
        "; Each section tests a different PA value.",
        "; Look for the section with most consistent",
        "; line width - corners should be sharp without",
        "; under/over extrusion.",
        ";",
        "; ========================================",
        "",
        "G90 ; Absolute positioning",
        "M82 ; Absolute extrusion mode",
        "",
        "; Home all axes",
        "G28 ; Home all axes",
        "",
        "; Set bed temperature and wait",
        f"M140 S{bed_temp:.0f} ; Set bed temperature",
        f"M190 S{bed_temp:.0f} ; Wait for bed temperature",
        "",
        "; Set nozzle temperature and wait",
        f"M104 S{nozzle_temp:.0f} ; Set nozzle temperature",
        f"M109 S{nozzle_temp:.0f} ; Wait for nozzle temperature",
        "",
        "; Set initial pressure advance",
        f"SET_PRESSURE_ADVANCE ADVANCE={pressure_advance:.4f} SMOOTH_TIME={smooth_time:.3f}",
        "",
        "; Prime line",
        "G1 Z5 F3000 ; Lift nozzle",
        "G1 X10 Y10 F6000 ; Move to start position",
        "G1 Z0.3 F3000 ; Lower to first layer height",
        "G1 X200 E20 F1500 ; Prime line",
        "G1 Z2 F3000 ; Lift nozzle",
        "G1 X10 F6000 ; Move away",
        "",
        "; Set fan speed",
        f"M106 S{int(fan_speed * 255 / 100)} ; Set fan to {fan_speed}%",
        "",
        "; Start printing",
        "G92 E0 ; Reset extruder position",
        "",
    ]
    return "\n".join(lines)


def generate_pa_test_section(
    pa_value: float,
    section_num: int,
    start_x: float,
    start_y: float,
    line_length: float,
    line_spacing: float,
    line_count: int,
    layer_height: float,
    nozzle_diameter: float,
    print_speed: int,
    smooth_time: float = 0.040
) -> str:
    """Generate G-code for a single PA test section."""
    lines = [
        "",
        f"; ========================================",
        f"; PA TEST SECTION {section_num}: PA={pa_value:.4f}",
        f"; ========================================",
        f"SET_PRESSURE_ADVANCE ADVANCE={pa_value:.4f} SMOOTH_TIME={smooth_time:.3f}",
        "",
    ]
    
    e_pos = 0.0
    
    for i in range(line_count):
        y_pos = start_y + (i * line_spacing)
        
        lines.append(f"; Test line {i + 1}")
        lines.append(f"G1 X{start_x:.2f} Y{y_pos:.2f} F6000")
        lines.append(f"G1 X{start_x + line_length:.2f} Y{y_pos:.2f} E{e_pos + line_length * 0.05:.3f} F{print_speed * 60}")
        e_pos += line_length * 0.05
        
        if i < line_count - 1:
            lines.append(f"G1 X{start_x + line_length + 5:.2f} Y{y_pos:.2f} F6000")
    
    lines.append("")
    return "\n".join(lines)


def generate_pattern_section(
    pa_value: float,
    section_num: int,
    start_x: float,
    start_y: float,
    pattern_size: float,
    layer_height: float,
    nozzle_diameter: float,
    print_speed: int,
    smooth_time: float = 0.040
) -> str:
    """Generate G-code for a pattern section showing PA effects on corners."""
    lines = [
        "",
        f"; ========================================",
        f"; PA PATTERN SECTION {section_num}: PA={pa_value:.4f}",
        f"; ========================================",
        f"SET_PRESSURE_ADVANCE ADVANCE={pa_value:.4f} SMOOTH_TIME={smooth_time:.3f}",
        "",
    ]
    
    e_pos = 0.0
    square_size = pattern_size / 3
    
    for square_num in range(3):
        sq_x = start_x + (square_num * (square_size + 2))
        sq_y = start_y
        
        lines.append(f"; Square {square_num + 1}")
        lines.append(f"G1 X{sq_x:.2f} Y{sq_y:.2f} F6000")
        
        perimeter = 4 * square_size
        extrusion_per_side = square_size * layer_height * nozzle_diameter / (nozzle_diameter * layer_height)
        
        lines.append(f"G1 X{sq_x + square_size:.2f} Y{sq_y:.2f} E{e_pos + extrusion_per_side:.3f} F{print_speed * 60}")
        e_pos += extrusion_per_side
        lines.append(f"G1 X{sq_x + square_size:.2f} Y{sq_y + square_size:.2f} E{e_pos + extrusion_per_side:.3f}")
        e_pos += extrusion_per_side
        lines.append(f"G1 X{sq_x:.2f} Y{sq_y + square_size:.2f} E{e_pos + extrusion_per_side:.3f}")
        e_pos += extrusion_per_side
        lines.append(f"G1 X{sq_x:.2f} Y{sq_y:.2f} E{e_pos + extrusion_per_side:.3f}")
        e_pos += extrusion_per_side
        lines.append("")
    
    return "\n".join(lines)


def generate_speed_test_section(
    pa_value: float,
    section_num: int,
    start_x: float,
    start_y: float,
    line_length: float,
    line_spacing: float,
    layer_height: float,
    nozzle_diameter: float,
    speeds: list,
    smooth_time: float = 0.040
) -> str:
    """Generate G-code for speed variation test at a specific PA value."""
    lines = [
        "",
        f"; ========================================",
        f"; PA SPEED TEST SECTION {section_num}: PA={pa_value:.4f}",
        f"; ========================================",
        f"SET_PRESSURE_ADVANCE ADVANCE={pa_value:.4f} SMOOTH_TIME={smooth_time:.3f}",
        "",
    ]
    
    e_pos = 0.0
    
    for i, speed in enumerate(speeds):
        y_pos = start_y + (i * line_spacing)
        
        lines.append(f"; Speed test line at {speed} mm/s")
        lines.append(f"G1 X{start_x:.2f} Y{y_pos:.2f} F6000")
        lines.append(f"G1 X{start_x + line_length:.2f} Y{y_pos:.2f} E{e_pos + line_length * 0.05:.3f} F{speed * 60}")
        e_pos += line_length * 0.05
    
    lines.append("")
    return "\n".join(lines)


def generate_end_gcode() -> str:
    """Generate end G-code for PA calibration."""
    lines = [
        "",
        "; ========================================",
        "; END G-CODE",
        "; ========================================",
        "",
        "; Reset pressure advance to default",
        "SET_PRESSURE_ADVANCE ADVANCE=0",
        "",
        "; Turn off heaters",
        "M104 S0 ; Turn off nozzle heater",
        "M140 S0 ; Turn off bed heater",
        "M106 S0 ; Turn off fan",
        "",
        "; Park nozzle",
        "G1 Z50 F3000 ; Lift nozzle",
        "G1 X10 Y200 F6000 ; Park position",
        "",
        "; Disable motors",
        "M84 ; Disable motors",
        "",
        "; ========================================",
        "; PRESSURE ADVANCE CALIBRATION COMPLETE",
        "; ========================================",
        ";",
        "; How to interpret results:",
        ";",
        "; Look for the section with:",
        ";  1. Most consistent line width",
        ";  2. Sharp corners without bulging",
        ";  3. No gaps at line starts",
        ";  4. No blobs at line ends",
        ";",
        "; DIRECT DRIVE: Typical PA = 0.02-0.06",
        "; BOWDEN: Typical PA = 0.3-0.7",
        ";",
        "; After finding optimal PA, add to your",
        "; printer.cfg under [extruder]:",
        ";   pressure_advance: <your_value>",
        ";   pressure_advance_smooth_time: 0.040",
        ";",
        "; ========================================",
    ]
    return "\n".join(lines)


def generate_pa_calibration(
    hotend_type: HotendType,
    bed_temp: float,
    nozzle_temp: float,
    min_pa: Optional[float] = None,
    max_pa: Optional[float] = None,
    pa_step: Optional[float] = None,
    smooth_time: float = 0.040,
    layer_height: float = 0.2,
    nozzle_diameter: float = 0.4,
    print_speed: int = 60,
    fan_speed: int = 100,
    line_length: float = 40.0,
    lines_per_section: int = 3,
    line_spacing: float = 2.0,
    base_x: float = 30.0,
    base_y: float = 20.0
) -> str:
    """Generate complete PA calibration G-code."""
    config = HOTEND_PA_CONFIGS[hotend_type]
    
    min_pa_val = min_pa if min_pa is not None else config.min_pa
    max_pa_val = max_pa if max_pa is not None else config.max_pa
    step_val = pa_step if pa_step is not None else config.step
    
    pa_values = []
    current_pa = min_pa_val
    while current_pa <= max_pa_val + 0.0001:
        pa_values.append(round(current_pa, 4))
        current_pa += step_val
    
    if not pa_values:
        print("[ERR] No PA values generated. Check min/max/step values.", file=sys.stderr)
        sys.exit(1)
    
    gcode_parts = []
    
    gcode_parts.append(generate_start_gcode(
        bed_temp=bed_temp,
        nozzle_temp=nozzle_temp,
        fan_speed=fan_speed,
        pressure_advance=pa_values[0],
        smooth_time=smooth_time
    ))
    
    gcode_parts.append("")
    gcode_parts.append("; PA Calibration Configuration:")
    gcode_parts.append(f";   Hotend type: {hotend_type.value}")
    gcode_parts.append(f";   PA range: {min_pa_val:.4f} to {max_pa_val:.4f}")
    gcode_parts.append(f";   PA step: {step_val:.4f}")
    gcode_parts.append(f";   Total PA values tested: {len(pa_values)}")
    gcode_parts.append(f";   Layer height: {layer_height}mm")
    gcode_parts.append(f";   Nozzle diameter: {nozzle_diameter}mm")
    gcode_parts.append(f";   Print speed: {print_speed}mm/s")
    gcode_parts.append(f";   Smooth time: {smooth_time}s")
    gcode_parts.append(f";   Bed temperature: {bed_temp:.0f}°C")
    gcode_parts.append(f";   Nozzle temperature: {nozzle_temp:.0f}°C")
    gcode_parts.append(f";   Fan speed: {fan_speed}%")
    gcode_parts.append("")
    gcode_parts.append(f"; Recommended PA range for {hotend_type.value}:")
    gcode_parts.append(f";   {config.recommended_range[0]:.3f} - {config.recommended_range[1]:.3f}")
    gcode_parts.append("")
    
    current_y = base_y
    section_height = lines_per_section * line_spacing + 5
    pattern_size = 30.0
    
    gcode_parts.append("; ========================================")
    gcode_parts.append("; PART 1: LINE WIDTH CONSISTENCY TEST")
    gcode_parts.append("; ========================================")
    
    for i, pa_val in enumerate(pa_values):
        section_gcode = generate_pa_test_section(
            pa_value=pa_val,
            section_num=i + 1,
            start_x=base_x,
            start_y=current_y,
            line_length=line_length,
            line_spacing=line_spacing,
            line_count=lines_per_section,
            layer_height=layer_height,
            nozzle_diameter=nozzle_diameter,
            print_speed=print_speed,
            smooth_time=smooth_time
        )
        
        pa_label = f"PA={pa_val:.4f}"
        label_gcode = f"; Label: {pa_label}\n; Print label on side of section {i + 1}"
        
        gcode_parts.append(section_gcode)
        gcode_parts.append(label_gcode)
        
        current_y += section_height
    
    current_y += 10
    gcode_parts.append("")
    gcode_parts.append("; ========================================")
    gcode_parts.append("; PART 2: CORNER QUALITY TEST")
    gcode_parts.append("; ========================================")
    
    for i, pa_val in enumerate(pa_values):
        pattern_gcode = generate_pattern_section(
            pa_value=pa_val,
            section_num=i + 1,
            start_x=base_x,
            start_y=current_y,
            pattern_size=pattern_size,
            layer_height=layer_height,
            nozzle_diameter=nozzle_diameter,
            print_speed=print_speed,
            smooth_time=smooth_time
        )
        gcode_parts.append(pattern_gcode)
        current_y += pattern_size + 5
    
    current_y += 10
    gcode_parts.append("")
    gcode_parts.append("; ========================================")
    gcode_parts.append("; PART 3: SPEED VARIATION TEST")
    gcode_parts.append("; Tests PA behavior at different speeds")
    gcode_parts.append("; ========================================")
    
    speed_test_pas = [pa_values[0], pa_values[len(pa_values)//2], pa_values[-1]] if len(pa_values) >= 3 else pa_values
    test_speeds = [30, 60, 100]
    
    for i, pa_val in enumerate(speed_test_pas):
        speed_gcode = generate_speed_test_section(
            pa_value=pa_val,
            section_num=i + 1,
            start_x=base_x,
            start_y=current_y,
            line_length=line_length,
            line_spacing=line_spacing,
            layer_height=layer_height,
            nozzle_diameter=nozzle_diameter,
            speeds=test_speeds,
            smooth_time=smooth_time
        )
        gcode_parts.append(speed_gcode)
        current_y += len(test_speeds) * line_spacing + 5
    
    gcode_parts.append(generate_end_gcode())
    
    return "\n".join(gcode_parts)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate Pressure Advance calibration G-code for Klipper firmware."
    )
    parser.add_argument(
        "--hotend", "-e",
        type=str,
        required=True,
        choices=[h.value for h in HotendType],
        help="Hotend type: direct or bowden"
    )
    parser.add_argument(
        "--output", "-o",
        type=str,
        help="Output G-code file path (default: stdout)"
    )
    parser.add_argument(
        "--bed-temp",
        type=float,
        default=60.0,
        help="Bed temperature in °C (default: 60)"
    )
    parser.add_argument(
        "--nozzle-temp",
        type=float,
        default=210.0,
        help="Nozzle temperature in °C (default: 210)"
    )
    parser.add_argument(
        "--min-pa",
        type=float,
        help="Minimum PA value to test (default: 0.0 for direct, 0.0 for bowden)"
    )
    parser.add_argument(
        "--max-pa",
        type=float,
        help="Maximum PA value to test (default: 0.1 for direct, 1.0 for bowden)"
    )
    parser.add_argument(
        "--step",
        type=float,
        help="PA step between sections (default: 0.005 for direct, 0.02 for bowden)"
    )
    parser.add_argument(
        "--smooth-time",
        type=float,
        default=0.040,
        help="Pressure advance smooth time in seconds (default: 0.040)"
    )
    parser.add_argument(
        "--layer-height",
        type=float,
        default=0.2,
        help="Layer height in mm (default: 0.2)"
    )
    parser.add_argument(
        "--nozzle-diameter",
        type=float,
        default=0.4,
        help="Nozzle diameter in mm (default: 0.4)"
    )
    parser.add_argument(
        "--speed",
        type=int,
        default=60,
        help="Print speed in mm/s (default: 60)"
    )
    parser.add_argument(
        "--fan",
        type=int,
        default=100,
        help="Fan speed percentage (default: 100)"
    )
    
    args = parser.parse_args()
    
    try:
        hotend_type = HotendType(args.hotend.lower())
    except ValueError:
        print(f"[ERR] Invalid hotend type: {args.hotend}", file=sys.stderr)
        sys.exit(1)
    
    config = HOTEND_PA_CONFIGS[hotend_type]
    
    print(f"Generating PA calibration for: {hotend_type.value} drive", file=sys.stderr)
    print(f"PA range: {args.min_pa or config.min_pa:.4f} - {args.max_pa or config.max_pa:.4f}", file=sys.stderr)
    
    gcode = generate_pa_calibration(
        hotend_type=hotend_type,
        bed_temp=args.bed_temp,
        nozzle_temp=args.nozzle_temp,
        min_pa=args.min_pa,
        max_pa=args.max_pa,
        pa_step=args.step,
        smooth_time=args.smooth_time,
        layer_height=args.layer_height,
        nozzle_diameter=args.nozzle_diameter,
        print_speed=args.speed,
        fan_speed=args.fan
    )
    
    if args.output:
        with open(args.output, "w", encoding="utf-8") as f:
            f.write(gcode)
        print(f"G-code written to: {args.output}", file=sys.stderr)
    else:
        print(gcode)


if __name__ == "__main__":
    main()
