#!/usr/bin/env python3
"""
resonant_frequency_test.py

Generate G-code for measuring printer resonant frequencies using an accelerometer
or by printing vibration test patterns. Helps identify ringing frequencies for
input shaping calibration.

Usage:
    python tools/resonant_frequency_test.py --axis x
    python tools/resonant_frequency_test.py --axis y --output resonance_test.gcode
    python tools/resonant_frequency_test.py --axis both --accel-range 500-10000
    python tools/resonant_frequency_test.py --type pattern --freq-range 20-100
"""

import argparse
import sys
from dataclasses import dataclass
from enum import Enum
from typing import Optional


class TestType(Enum):
    ACCELEROMETER = "accel"
    PATTERN = "pattern"


class TestAxis(Enum):
    X = "x"
    Y = "y"
    BOTH = "both"


@dataclass
class ResonanceTestConfig:
    min_freq: float
    max_freq: float
    freq_step: float
    accel_per_hz: float
    max_accel: float
    test_speed: float
    line_length: float


DEFAULT_CONFIG = ResonanceTestConfig(
    min_freq=10.0,
    max_freq=150.0,
    freq_step=2.0,
    accel_per_hz=75.0,
    max_accel=15000.0,
    test_speed=100.0,
    line_length=100.0
)


def generate_accel_start_gcode(
    axis: TestAxis,
    accel_chip: str = "adxl345",
    bed_temp: float = 60.0,
    nozzle_temp: float = 210.0
) -> str:
    lines = [
        "; Resonance Frequency Test G-code",
        "; Generated by OpenPrint3D resonant_frequency_test.py",
        "; ========================================",
        ";",
        "; This test uses an accelerometer to measure",
        "; resonant frequencies of the printer motion system.",
        "; Results are used to configure input shapers.",
        ";",
        "; Requires: ADXL345 or similar accelerometer",
        "; Requires: Klipper with resonance_test_extension",
        ";",
        "; ========================================",
        "",
        "G90 ; Absolute positioning",
        "M82 ; Absolute extrusion mode",
        "",
        "; Home all axes",
        "G28 ; Home all axes",
        "",
        "; Set temperatures for printing test marker",
        f"M140 S{bed_temp:.0f} ; Set bed temperature",
        f"M104 S{nozzle_temp:.0f} ; Set nozzle temperature",
        "",
        "; Initialize accelerometer",
        f"ACCELEROMETER_QUERY CHIP={accel_chip}",
        "",
        "; Move to center of bed",
        "G1 X100 Y100 Z10 F6000",
        "",
        f"; Test axis: {axis.value.upper()}",
        "",
    ]
    return "\n".join(lines)


def generate_resonance_test_gcode(
    axis: TestAxis,
    config: ResonanceTestConfig,
    accel_chip: str = "adxl345",
    test_points: int = 1
) -> str:
    lines = [
        "; ========================================",
        "; RESONANCE MEASUREMENT TEST",
        "; ========================================",
        "",
    ]
    
    if axis == TestAxis.BOTH:
        axes = [TestAxis.X, TestAxis.Y]
    else:
        axes = [axis]
    
    for test_axis in axes:
        lines.append(f"; Testing {test_axis.value.upper()} axis")
        lines.append("")
        
        if test_axis == TestAxis.X:
            lines.append(f"TEST_RESONANCES AXIS=X CHIP={accel_chip} FREQ_START={config.min_freq} FREQ_END={config.max_freq} HZ_PER_SEC={config.freq_step}")
        else:
            lines.append(f"TEST_RESONANCES AXIS=Y CHIP={accel_chip} FREQ_START={config.min_freq} FREQ_END={config.max_freq} HZ_PER_SEC={config.freq_step}")
        
        lines.append("")
        lines.append(f"; {test_axis.value.upper()} axis measurement complete")
        lines.append("")
    
    return "\n".join(lines)


def generate_pattern_test_start_gcode(
    bed_temp: float = 60.0,
    nozzle_temp: float = 210.0,
    fan_speed: int = 100
) -> str:
    lines = [
        "; Resonance Pattern Test G-code",
        "; Generated by OpenPrint3D resonant_frequency_test.py",
        "; ========================================",
        ";",
        "; This test prints patterns at varying speeds to",
        "; identify ringing artifacts caused by resonances.",
        ";",
        "; Without accelerometer: visually identify ringing",
        "; Measure distance between ringing artifacts to",
        "; calculate approximate resonant frequency.",
        ";",
        "; ========================================",
        "",
        "G90 ; Absolute positioning",
        "M82 ; Absolute extrusion mode",
        "",
        "; Home all axes",
        "G28 ; Home all axes",
        "",
        "; Set temperatures",
        f"M140 S{bed_temp:.0f} ; Set bed temperature",
        f"M190 S{bed_temp:.0f} ; Wait for bed temperature",
        f"M104 S{nozzle_temp:.0f} ; Set nozzle temperature",
        f"M109 S{nozzle_temp:.0f} ; Wait for nozzle temperature",
        "",
        "; Prime line",
        "G1 Z5 F3000 ; Lift nozzle",
        "G1 X10 Y10 F6000 ; Move to start position",
        "G1 Z0.3 F3000 ; Lower to first layer height",
        "G1 X200 E20 F1500 ; Prime line",
        "G1 Z2 F3000 ; Lift nozzle",
        "G1 X10 F6000 ; Move away",
        "",
        f"M106 S{int(fan_speed * 255 / 100)} ; Set fan to {fan_speed}%",
        "",
        "G92 E0 ; Reset extruder position",
        "",
    ]
    return "\n".join(lines)


def generate_ringing_test_pattern(
    start_x: float,
    start_y: float,
    line_length: float,
    speeds: list,
    layer_height: float = 0.2,
    nozzle_diameter: float = 0.4,
    direction: str = "x"
) -> str:
    lines = []
    e_pos = 0.0
    
    for i, speed in enumerate(speeds):
        y_pos = start_y + (i * 4)
        
        lines.append(f"; Speed test: {speed} mm/s, direction: {direction.upper()}")
        lines.append(f"G1 X{start_x:.1f} Y{y_pos:.1f} F6000")
        lines.append(f"G1 Z{layer_height:.2f} F3000")
        
        extrusion = line_length * layer_height * nozzle_diameter / (nozzle_diameter * layer_height) * 0.8
        
        if direction.lower() == "x":
            lines.append(f"G1 X{start_x + line_length:.1f} Y{y_pos:.1f} E{e_pos + extrusion:.3f} F{speed * 60}")
            lines.append(f"G1 X{start_x:.1f} Y{y_pos:.1f} E{e_pos + extrusion * 2:.3f} F{speed * 60}")
        else:
            lines.append(f"G1 X{start_x:.1f} Y{y_pos + line_length:.1f} E{e_pos + extrusion:.3f} F{speed * 60}")
            lines.append(f"G1 X{start_x:.1f} Y{y_pos:.1f} E{e_pos + extrusion * 2:.3f} F{speed * 60}")
        
        e_pos += extrusion * 2
        lines.append("")
    
    return "\n".join(lines)


def generate_vibration_tower(
    config: ResonanceTestConfig,
    axis: TestAxis,
    layer_height: float = 0.2,
    nozzle_diameter: float = 0.4,
    tower_width: float = 25.0,
    tower_depth: float = 25.0,
    base_x: float = 30.0,
    base_y: float = 30.0
) -> str:
    lines = []
    
    speeds = [40, 60, 80, 100, 120, 150]
    
    lines.append("; ========================================")
    lines.append("; VIBRATION/RINGING TEST TOWER")
    lines.append("; ========================================")
    lines.append(f"; Testing speeds: {speeds} mm/s")
    lines.append(f"; Each layer tests different speed")
    lines.append("; Look for ringing patterns on surfaces")
    lines.append("; ========================================")
    lines.append("")
    
    for layer, speed in enumerate(speeds):
        z_height = (layer + 1) * layer_height
        lines.append(f"; Layer {layer + 1} - Speed: {speed} mm/s")
        lines.append(f"G1 Z{z_height:.2f} F3000")
        
        e_pos = 0.0
        perimeter = 2 * (tower_width + tower_depth)
        extrusion = perimeter * layer_height / nozzle_diameter * 0.5
        
        lines.append(f"G1 X{base_x:.1f} Y{base_y:.1f} F6000")
        
        for wall in range(2):
            lines.append(f"G1 X{base_x + tower_width:.1f} Y{base_y:.1f} E{e_pos + extrusion/4:.3f} F{speed * 60}")
            e_pos += extrusion / 4
            lines.append(f"G1 X{base_x + tower_width:.1f} Y{base_y + tower_depth:.1f} E{e_pos + extrusion/4:.3f}")
            e_pos += extrusion / 4
            lines.append(f"G1 X{base_x:.1f} Y{base_y + tower_depth:.1f} E{e_pos + extrusion/4:.3f}")
            e_pos += extrusion / 4
            lines.append(f"G1 X{base_x:.1f} Y{base_y:.1f} E{e_pos + extrusion/4:.3f}")
            e_pos += extrusion / 4
        
        lines.append("")
    
    return "\n".join(lines)


def generate_end_gcode() -> str:
    lines = [
        "",
        "; ========================================",
        "; END G-CODE",
        "; ========================================",
        "",
        "M104 S0 ; Turn off nozzle heater",
        "M140 S0 ; Turn off bed heater",
        "M106 S0 ; Turn off fan",
        "",
        "G1 Z50 F3000 ; Lift nozzle",
        "G1 X10 Y200 F6000 ; Park position",
        "",
        "M84 ; Disable motors",
        "",
        "; ========================================",
        "; RESONANCE TEST COMPLETE",
        "; ========================================",
        ";",
        "; Analyzing results:",
        ";",
        "; WITH ACCELEROMETER:",
        ";  - Run: python ~/klipper/scripts/graph_accelerometer.py",
        ";  - Check resonance peaks in generated graphs",
        ";  - Note primary resonant frequencies",
        ";",
        "; WITHOUT ACCELEROMETER (pattern test):",
        ";  - Look for visible ringing/ghosting patterns",
        ";  - Measure spacing between ringing artifacts",
        ";  - Frequency = speed / spacing (mm/s / mm)",
        ";",
        "; Use results to configure input shaper:",
        ";  SHAPER_TYPE: ei, 2hum, zvd, mzv, etc.",
        ";  SHAPER_FREQ_X: <X axis frequency>",
        ";  SHAPER_FREQ_Y: <Y axis frequency>",
        ";",
        "; Common resonant frequencies:",
        ";  - CoreXY: typically 30-50 Hz",
        ";  - Cartesian: typically 25-40 Hz",
        ";  - Delta: typically 35-60 Hz",
        ";",
        "; ========================================",
    ]
    return "\n".join(lines)


def generate_ringing_calculation_guide() -> str:
    lines = [
        "",
        "; ========================================",
        "; RINGING FREQUENCY CALCULATION",
        "; ========================================",
        ";",
        "; If you see ringing patterns:",
        ";  1. Measure the distance between rings (mm)",
        ";  2. Note the printing speed (mm/s)",
        ";  3. Calculate frequency:",
        ";",
        ";     Frequency (Hz) = Speed / Ring_Spacing",
        ";",
        ";  Example:",
        ";     Speed = 60 mm/s",
        ";     Ring spacing = 1.5 mm",
        ";     Frequency = 60 / 1.5 = 40 Hz",
        ";",
        "; ========================================",
    ]
    return "\n".join(lines)


def generate_resonance_test(
    test_type: TestType,
    axis: TestAxis,
    config: ResonanceTestConfig,
    bed_temp: float = 60.0,
    nozzle_temp: float = 210.0,
    fan_speed: int = 100,
    accel_chip: str = "adxl345",
    layer_height: float = 0.2,
    nozzle_diameter: float = 0.4
) -> str:
    gcode_parts = []
    
    if test_type == TestType.ACCELEROMETER:
        gcode_parts.append(generate_accel_start_gcode(
            axis=axis,
            accel_chip=accel_chip,
            bed_temp=bed_temp,
            nozzle_temp=nozzle_temp
        ))
        gcode_parts.append(generate_resonance_test_gcode(
            axis=axis,
            config=config,
            accel_chip=accel_chip
        ))
    else:
        gcode_parts.append(generate_pattern_test_start_gcode(
            bed_temp=bed_temp,
            nozzle_temp=nozzle_temp,
            fan_speed=fan_speed
        ))
        
        gcode_parts.append("")
        gcode_parts.append("; Test Configuration:")
        gcode_parts.append(f";   Test type: Pattern (visual ringing detection)")
        gcode_parts.append(f";   Axis: {axis.value.upper()}")
        gcode_parts.append(f";   Layer height: {layer_height}mm")
        gcode_parts.append(f";   Nozzle diameter: {nozzle_diameter}mm")
        gcode_parts.append("")
        
        speeds = [40, 60, 80, 100, 120, 150, 180]
        
        if axis == TestAxis.BOTH or axis == TestAxis.X:
            gcode_parts.append("; ========================================")
            gcode_parts.append("; X-AXIS RINGING TEST")
            gcode_parts.append("; ========================================")
            gcode_parts.append(generate_ringing_test_pattern(
                start_x=20,
                start_y=20,
                line_length=config.test_speed,
                speeds=speeds,
                layer_height=layer_height,
                nozzle_diameter=nozzle_diameter,
                direction="x"
            ))
        
        if axis == TestAxis.BOTH or axis == TestAxis.Y:
            gcode_parts.append("; ========================================")
            gcode_parts.append("; Y-AXIS RINGING TEST")
            gcode_parts.append("; ========================================")
            gcode_parts.append(generate_ringing_test_pattern(
                start_x=20,
                start_y=100,
                line_length=config.test_speed,
                speeds=speeds,
                layer_height=layer_height,
                nozzle_diameter=nozzle_diameter,
                direction="y"
            ))
        
        gcode_parts.append(generate_vibration_tower(
            config=config,
            axis=axis,
            layer_height=layer_height,
            nozzle_diameter=nozzle_diameter
        ))
        
        gcode_parts.append(generate_ringing_calculation_guide())
    
    gcode_parts.append(generate_end_gcode())
    
    return "\n".join(gcode_parts)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate G-code for measuring printer resonant frequencies."
    )
    parser.add_argument(
        "--type", "-t",
        type=str,
        choices=[t.value for t in TestType],
        default=TestType.PATTERN.value,
        help="Test type: accel (accelerometer) or pattern (visual)"
    )
    parser.add_argument(
        "--axis", "-a",
        type=str,
        choices=[ax.value for ax in TestAxis],
        default=TestAxis.BOTH.value,
        help="Axis to test: x, y, or both"
    )
    parser.add_argument(
        "--output", "-o",
        type=str,
        help="Output G-code file path (default: stdout)"
    )
    parser.add_argument(
        "--min-freq",
        type=float,
        default=10.0,
        help="Minimum frequency for accelerometer test (default: 10 Hz)"
    )
    parser.add_argument(
        "--max-freq",
        type=float,
        default=150.0,
        help="Maximum frequency for accelerometer test (default: 150 Hz)"
    )
    parser.add_argument(
        "--freq-step",
        type=float,
        default=2.0,
        help="Frequency step for accelerometer test (default: 2 Hz/sec)"
    )
    parser.add_argument(
        "--accel-chip",
        type=str,
        default="adxl345",
        help="Accelerometer chip name (default: adxl345)"
    )
    parser.add_argument(
        "--bed-temp",
        type=float,
        default=60.0,
        help="Bed temperature in °C (default: 60)"
    )
    parser.add_argument(
        "--nozzle-temp",
        type=float,
        default=210.0,
        help="Nozzle temperature in °C (default: 210)"
    )
    parser.add_argument(
        "--fan",
        type=int,
        default=100,
        help="Fan speed percentage (default: 100)"
    )
    parser.add_argument(
        "--layer-height",
        type=float,
        default=0.2,
        help="Layer height in mm for pattern test (default: 0.2)"
    )
    parser.add_argument(
        "--nozzle-diameter",
        type=float,
        default=0.4,
        help="Nozzle diameter in mm (default: 0.4)"
    )
    
    args = parser.parse_args()
    
    try:
        test_type = TestType(args.type.lower())
        axis = TestAxis(args.axis.lower())
    except ValueError as e:
        print(f"[ERR] Invalid argument: {e}", file=sys.stderr)
        sys.exit(1)
    
    config = ResonanceTestConfig(
        min_freq=args.min_freq,
        max_freq=args.max_freq,
        freq_step=args.freq_step,
        accel_per_hz=DEFAULT_CONFIG.accel_per_hz,
        max_accel=DEFAULT_CONFIG.max_accel,
        test_speed=DEFAULT_CONFIG.test_speed,
        line_length=DEFAULT_CONFIG.line_length
    )
    
    print(f"Generating resonance test: {test_type.value}, axis: {axis.value}", file=sys.stderr)
    
    gcode = generate_resonance_test(
        test_type=test_type,
        axis=axis,
        config=config,
        bed_temp=args.bed_temp,
        nozzle_temp=args.nozzle_temp,
        fan_speed=args.fan,
        accel_chip=args.accel_chip,
        layer_height=args.layer_height,
        nozzle_diameter=args.nozzle_diameter
    )
    
    if args.output:
        with open(args.output, "w", encoding="utf-8") as f:
            f.write(gcode)
        print(f"G-code written to: {args.output}", file=sys.stderr)
    else:
        print(gcode)


if __name__ == "__main__":
    main()