#!/usr/bin/env python3
"""
slicer_translator.py

Translate Cura slicer settings to PrusaSlicer, OrcaSlicer, and Bambu Studio formats.

Usage:
    python tools/slicer_translator.py --input cura_settings.json --output prusaslicer
    python tools/slicer_translator.py --input cura_settings.json --output orca
    python tools/slicer_translator.py --input cura_settings.json --output bambu
    python tools/slicer_translator.py --input cura_settings.json --output all --dir ./converted
"""

import argparse
import json
import sys
from pathlib import Path


CURA_TO_PRUSASLICER = {
    "print_temperature": "temperature",
    "print_temperature_layer_0": "temperature",
    "bed_temperature": "bed_temperature",
    "bed_temperature_layer_0": "bed_temperature",
    "fan_speed": "fan_speed",
    "fan_speed_layer_0": "fan_speed",
    "material": "filament_type",
    "print_speed": "speed_print",
    "travel_speed": "speed_travel",
    "infill_sparse_density": "fill_density",
    "wall_thickness": "perimeters",
    "layer_height": "layer_height",
    "bottom_layers": "bottom_solid_layers",
    "top_layers": "top_solid_layers",
    "infill_pattern": "fill_pattern",
    "wall_pattern": "external_fill_pattern",
    " retraction_enable": "retract_length",
    "retraction_speed": "retract_speed",
    "retraction_distance": "retract_length",
    "retraction_min_travel": "retract_before_travel",
    "retraction_combing": "retract_when_changing_layers",
    "skin_overlap": "infill_overlap",
    "infill_before_walls": "infill_optimizer",
    "support_enable": "support_enable",
    "support_type": "support_type",
    "support_angle": "support_angle",
    "support_line_distance": "support_density",
    "platform_adhesion": "bed_type",
    "brim_width": "brim_width",
    "raft_margin": "raft_offset",
    "skirt_line_count": "skirt_loops",
    "skirt_gap": "skirt_distance",
    "cool_fan_enabled": "fan_always_on",
    "cool_fan_speed": "fan_speed",
    "cool_fan_full_layer": "fan_full_height",
    "outer_before_inner_walls": "wall_order",
    "fill_perimeter_gaps": "fill_perimeter_gaps",
    "ironing_enabled": "ironing",
    "ironing_spacing": "ironing_flowrate",
    "ironing_angle": "ironing_angle",
    "sequence": "print_sequence",
    "outer_inset_first": "perimeter_extrusion_mode",
    "z_seam_x": "seam_x",
    "z_seam_y": "seam_y",
    "z_seam_corner": "seam_corner_type",
    "skin_outer_before_walls": "skin_outer_before_walls",
    "magic_spiralize": "spiral_mode",
    "magic_mesh_surface_mode": "mesh_mode",
    "fill_disconnected_areas": "fill_not_connected_area",
    "travel_avoid_distance": "travel_avoid_distance",
    "travel_compensate_within_threads": "travel_compensate_inline",
    "pre_warm": "wait_for_prime",
    "wall_0_wipe_dist": "wipe_extra_perimeter",
    "fill_backwards": "fill_backwards",
    "fill_ordered": "infill_every_layers",
    "force_travel": "output_only_first_layer",
    "keep_alive_fan_speed": "keep_fan_continuous",
    "cool_min_feedrate": "min_fan_speed_layer_time",
    "cool_min_layer_time": "min_layer_time",
    "cool_lift_head": "cool_lift_head",
    "infill_hollow": "infill_hollow",
    "auto_temp_match": "automatic_cooling",
    "resonance_compensation": "resonance_compensation",
    "adaptive_layer_height": "adaptive_layer_height",
    "adaptive_layer_height_variation": "adaptiv_layer_height_variation",
    "adaptive_layer_height_variation_step": "adaptiv_layer_height_variation_step",
    "acceleration_enabled": "acceleration_enable",
    "acceleration_print": "acceleration_print",
    "acceleration_travel": "acceleration_travel",
    "acceleration_layer_0": "acceleration_first_layer",
    "acceleration_infill": "acceleration_infill",
    "acceleration_wall": "acceleration_perimeter",
    "acceleration_wall_0": "acceleration_prime",
    "acceleration_topbottom": "acceleration_top_bottom",
    "acceleration_support": "acceleration_support",
    "acceleration_support_interface": "acceleration_support_interface",
    "jerk_enabled": "jerk_enable",
    "jerk_print": "jerk_print",
    "jerk_travel": "jerk_travel",
    "jerk_layer_0": "jerk_first_layer",
    "jerk_infill": "jerk_infill",
    "jerk_wall": "jerk_perimeter",
    "jerk_topbottom": "jerk_top_bottom",
    "jerk_support": "jerk_support",
    "jerk_support_interface": "jerk_support_interface",
    "meshfix_maximum_resolution": "resolution",
    "meshfix_maximum_deviation": "maximum_deviation",
    "meshfix_maximum_length": "max_length",
    "meshfix_ignore_small_z": "ignore_small_z",
    "multiple_mesh_offset": "multiple_mesh_offset",
    "carve_multiple_volumes": "carve_multiple_volumes",
    "cut_off_mesh_grounds": "cut_off_bottom",
    "slicing_tolerance": "slicing_tolerance",
    "max_extrusion_before_wipe": "max_extrusion_before_wipe",
    "wipe_and_copy": "wipe_and_copy",
    "wipe_enabled": "wipe_enable",
    "wipe_extra_perimeter": "wipe_extra_perimeter",
    "wipe_only_same_layer": "wipe_only_same_layer",
    "wipe_before_travel": "wipe_before_travel",
    "ooze_shield_enabled": "ooze_shield_enabled",
    "ooze_shield_angle": "ooze_shield_angle",
    "ooze_shield_dist": "ooze_shield_dist",
    "minimum_sparse_infill_area": "min_sparse_infill_area",
    "sparse_infill_fan_threshold": "sparse_infill_fan_threshold",
    "sparse_infill_line_distance": "sparse_infill_line_distance",
    "sparse_infill_pattern": "sparse_infill_pattern",
    "sparse_infill_density": "fill_density",
    "sparse_infill_angles": "infill_angles",
    "infill_extruder": "infill_extruder",
    "infill_first": "infill_first",
    "min_infill_area": "min_infill_area",
    "min_skin_width_for_expansion": "skin_expansion",
    "bridge_settings_enabled": "bridge_settings_enabled",
    "bridge_angle": "bridge_angle",
    "bridge_skin_speed": "bridge_skin_speed",
    "bridge_skin_supported": "bridge_skin_supported",
    "bridge_fan_enabled": "bridge_fan_enabled",
    "bridge_fan_speed": "bridge_fan_speed",
    "layer_0_z_offset": "z_offset",
    "initial_layer_line_width_factor": "initial_layer_line_width",
    "initial_layer_print_speed": "initial_layer_speed",
    "initial_layer_speed_factor": "initial_layer_speed",
    "travel_speed": "travel_speed",
    "outer_inset_first": "outer_first",
    "support_extruder_nr": "support_extruder",
    "support_infill_extruder_nr": "support_infill_extruder",
    "support_roof_extruder_nr": "support_roof_extruder",
    "support_bottom_extruder_nr": "support_bottom_extruder",
    "support_offset": "support_offset",
    "support_roof_offset": "support_roof_offset",
    "support_bottom_offset": "support_bottom_offset",
    "support_join_distance": "support_join_distance",
    "support_pattern": "support_pattern",
    "support_roof_pattern": "support_roof_pattern",
    "support_bottom_pattern": "support_bottom_pattern",
    "support_line_width": "support_line_width",
    "support_roof_line_width": "support_roof_line_width",
    "support_bottom_line_width": "support_bottom_line_width",
    "support_z_distance": "support_top_distance",
    "support_roof_z_distance": "support_roof_top_distance",
    "support_bottom_z_distance": "support_bottom_bottom_distance",
    "support_xy_distance": "support_xy_distance",
    "support_xy_overrides_z": "support_xy_overrides_support_z",
    "support_stair_step_height": "support_stair_step_enabled",
    "support_stair_step_height_value": "support_stair_step_height",
    "support_stair_step_width": "support_stair_step_width",
    "support_top_bottom_thickness": "support_thickness",
    "support_interface_thickness": "support_interface_thickness",
    "support_interface_skip_height": "support_interface_skip",
    "support_extruder_nr_layer_0": "first_layer_extruder",
    "support_roof_extruder_nr_layer_0": "support_roof_extruder",
    "support_bottom_extruder_nr_layer_0": "support_bottom_extruder",
    "support_use_xy_overrides_z": "support_use_xy_overrides_z",
    "prime_tower_enable": "prime_tower_enable",
    "prime_tower_size": "prime_tower_size",
    "prime_tower_min_volume": "prime_tower_min_volume",
    "prime_tower_position": "prime_tower_position",
    "prime_tower_brim_width": "prime_tower_brim_width",
    "prime_tower_wipe": "prime_tower_wipe",
    "raft_base_thickness": "raft_base_thickness",
    "raft_interface_thickness": "raft_interface_thickness",
    "raft_surface_layers": "raft_surface_layers",
    "raft_surface_thickness": "raft_surface_thickness",
    "raft_interface_linewidth": "raft_interface_linewidth",
    "raft_surface_linewidth": "raft_surface_linewidth",
    "raft_base_speed": "raft_base_speed",
    "raft_interface_speed": "raft_interface_speed",
    "raft_surface_speed": "raft_surface_speed",
    "raft_airgap": "raft_airgap",
    "raft_first_layer_density": "raft_first_layer_density",
    "raft_first_layer_expansion": "raft_first_layer_expansion",
    "brim_replaces_support": "brim_replaces_support",
    "brim_width": "brim_width",
    "brim_outside_only": "brim_outside_only",
    "brim_type": "brim_type",
    "skirt_gap": "skirt_gap",
    "skirt_line_count": "skirt_line_count",
    "skirt_minimal_length": "skirt_minimal_length",
    "skirt_brim_line_width": "skirt_brim_line_width",
    "abs_extruder_nr": "extruder_nr",
    "adhesion_type": "bed_type",
    "platform_surface_texture": "bed_surface",
    "platform_roof_layers": "raft_surface_layers",
    "z_seam_corner": "seam_corner_type",
    "z_seam_x": "seam_x",
    "z_seam_y": "seam_y",
    "z_seam_type": "seam_position",
    "offset_x": "machine_offset_x",
    "offset_y": "machine_offset_y",
    "xy_offset": "xy_offset",
    "xy_offset_layer_0": "xy_offset_layer_0",
    "hole_xy_offset": "hole_xy_offset",
    "extra_perimeter": "extra_perimeters",
    "extra_perimeter_odd_layers": "extra_perimeters_odd_layers",
    "min_feature_size": "min_feature_size",
    "min_outer_wall_flow": "min_outer_wall_flow",
    "min_inner_wall_flow": "min_inner_wall_flow",
    "inner_wall_line_width": "wall_line_width",
    "inner_wall_speed": "inner_wall_speed",
    "outer_wall_line_width": "outer_wall_line_width",
    "outer_wall_speed": "outer_wall_speed",
    "skin_line_width": "top_bottom_line_width",
    "skin_speed": "top_bottom_speed",
    "infill_line_width": "infill_line_width",
    "infill_speed": "infill_speed",
    "skirt_brim_speed": "skirt_brim_speed",
    "prime_blob_speed": "prime_blob_speed",
    "travel_speed": "travel_speed",
    "layer_start_x": "layer_start_x",
    "layer_start_y": "layer_start_y",
    "move_speed": "default_acceleration",
    "start_layers_method": "start_layers_method",
    "anti_ooze_address": "anti_ooze_pos",
    "flow_rate": "max_volumetric_speed",
    "wall_0_wipe_dist": "wipe_outer_before_outer_wall",
    "wipe_outer_before_outer_wall": "wipe_outer_before_outer_wall",
    "post_process": "post_process",
    "mesh_rotation_matrix": "mesh_rotation_matrix",
    "mira_enabled": "mira_enabled",
    "mira_extruder": "mira_extruder",
    "mira_mode": "mira_mode",
    "mira_seam_angle": "mira_seam_angle",
    "mira_seam_x": "mira_seam_x",
    "mira_seam_y": "mira_seam_y",
    "mira_offset_from_wall": "mira_offset",
    "mira_loop_cnt": "mira_loop_cnt",
    "mira_span_cnt": "mira_span_cnt",
    "mira_offset_radial": "mira_offset_radial",
    "conical_support_enabled": "conical_support_enabled",
    "conical_support_angle": "conical_support_angle",
    "conical_support_base_diameter": "conical_support_base_diameter",
    "conical_support_hole_diameter": "conical_support_hole_diameter",
    "select_by_mesh": "print_select",
    "exclude_tower": "print_exclude_tower",
    "mysql_enabled": "mysql_enabled",
    "mysql_server_url": "mysql_server_url",
    "mysql_server_port": "mysql_server_port",
    "mysql_server_database": "mysql_server_database",
    "mysql_server_user": "mysql_server_user",
    "mysql_server_password": "mysql_server_password",
    "cloud_api_enabled": "cloud_api_enabled",
    "cloud_sync_enabled": "cloud_sync_enabled",
    "print_sequence": "print_sequence",
    "infinite_skirt": "infinite_skirt",
    "alternate_extra_perimeter": "alternate_extra_perimeters",
    "uzzy_pillows_enabled": "fuzzy_skin_enabled",
    "uzzy_pillows_thickness": "fuzzy_skin_thickness",
    "uzzy_pillards_point_density": "fuzzy_skin_point_distance",
    "hair_not_supported_angle": "hair_no_support_angle",
    "hair_not_supported_distance": "hair_no_support_distance",
    "coasting_enable": "coasting_enable",
    "coasting_volume": "coasting_volume_min",
    "coasting_speed": "coasting_speed_min",
    "coasting_min_volume": "coasting_volume_min",
    "cross_infill_pocket_size": "cross_infill_pocket_size",
    "cross_infill_deterministic": "cross_infill_deterministic",
    "interlocking_accuracy": "interlocking_accuracy",
    "interlocking_orbital": "interlocking_orbital",
    "interlocking_bridge_rotation": "interlocking_bridge_rotation",
    "interlocking_enabled": "interlocking_enabled",
    "minimum_bottom_layers": "minimum_bottom_layers",
    "optimize_wall_printing_order": "optimize_wall_order",
    "paint_infill_extruder": "paint_infill_extruder",
    "paint_extruder": "paint_extruder",
    "wireframe_enabled": "wireframe_enabled",
    "wireframe_roof_speed": "wireframe_roof_speed",
    "wireframe_floor_speed": "wireframe_floor_speed",
    "wireframe_wall_speed": "wireframe_wall_speed",
    "wireframe_printspeed": "wireframe_printspeed",
    "wireframe_outline_speed": "wireframe_outline_speed",
    "wireframe_nozzle_cool_down": "wireframe_nozzle_cool_down",
    "wireframe_flatten": "wireframe_flatten",
    "wireframe_flow": "wireframe_flow",
    "wireframe_roof_flow": "wireframe_roof_flow",
    "wireframe_floor_flow": "wireframe_floor_flow",
    "wireframe_pressure": "wireframe_pressure",
    "wireframe_print_cool": "wireframe_print_cool",
    "wireframe_height": "wireframe_height",
    "wireframe_roof_height": "wireframe_roof_height",
    "wireframe_floor_height": "wireframe_floor_height",
    "wireframe_top_gate_overlap": "wireframe_top_gate_overlap",
    "wireframe_bottom_gate_overlap": "wireframe_bottom_gate_overlap",
    "wireframe_top_gate_flow": "wireframe_top_gate_flow",
    "wireframe_bottom_gate_flow": "wireframe_bottom_gate_flow",
    "wireframe_stroke_width": "wireframe_stroke_width",
    "wireframe_roof_inset": "wireframe_roof_inset",
    "wireframe_roof_layer": "wireframe_roof_layer",
    "wireframe_floor_layer": "wireframe_floor_layer",
    "wireframe_floor_overshoot": "wireframe_floor_overshoot",
    "wireframe_roof_overshoot": "wireframe_roof_overshoot",
    "wireframe_drag_along": "wireframe_drag_along",
    "wireframe_retract_dead_length": "wireframe_retrac_dead_length",
    "wireframe_hop": "wireframe_hop",
    "wireframe_hop_height": "wireframe_hop_height",
    "wireframe_hop_selection": "wireframe_hop_type",
    "stochastic_fill": "stochastic_fill",
    "minimum_sub_divs": "minimum_subdivision_line_count",
}

CURA_TO_ORCA = {
    "print_temperature": "nozzle_temperature",
    "print_temperature_layer_0": "nozzle_temperature_initial_layer",
    "bed_temperature": "bed_temperature",
    "bed_temperature_layer_0": "bed_temperature_initial_layer",
    "fan_speed": "fan_speed",
    "fan_speed_layer_0": "fan_speed_initial_layer",
    "material": "filament_type",
    "print_speed": "speed_print",
    "travel_speed": "speed_travel",
    "infill_sparse_density": "fill_density",
    "wall_thickness": "wall_loops",
    "layer_height": "layer_height",
    "bottom_layers": "bottom_shell_layers",
    "top_layers": "top_shell_layers",
    "infill_pattern": "infill_pattern",
    "wall_pattern": "wall_infill_order",
    "retraction_enable": "retraction_enable",
    "retraction_speed": "retract_speed",
    "retraction_distance": "retract_length",
    "retraction_min_travel": "retract_before_travel",
    "retraction_combing": "retraction_combing",
    "skin_overlap": "overlap",
    "support_enable": "enable_support",
    "support_type": "support_type",
    "support_angle": "support_threshold_angle",
    "support_line_distance": "support_density",
    "platform_adhesion": "adhesion_type",
    "brim_width": "brim_width",
    "raft_margin": "raft_offset",
    "skirt_line_count": "skirt_line_count",
    "skirt_gap": "skirt_gap",
    "cool_fan_enabled": "fan_always_on",
    "cool_fan_speed": "fan_speed",
    "cool_fan_full_layer": "full_fan_speed_layer",
    "outer_before_inner_walls": "wall_order",
    "fill_perimeter_gaps": "fill_perimeter_gaps",
    "ironing_enabled": "ironing_enabled",
    "ironing_spacing": "ironing_spacing",
    "ironing_angle": "ironing_angle",
    "sequence": "print_sequence",
    "outer_inset_first": "outer_wall_mode",
    "z_seam_x": "seam_x",
    "z_seam_y": "seam_y",
    "z_seam_corner": "seam_corner_type",
    "skin_outer_before_walls": "outer_before_inner_walls",
    "magic_spiralize": "spiral_mode",
    "magic_mesh_surface_mode": "surface_mode",
    "fill_disconnected_areas": "infill_not_covered_by_surface",
    "travel_avoid_distance": "travel_avoid_distance",
    "travel_compensate_within_threads": "travel_compensate_inside",
    "pre_warm": "wipe_while_priming",
    "wall_0_wipe_dist": "wipe_distance",
    "fill_backwards": "infill_direction",
    "fill_ordered": "infill_every_layers",
    "force_travel": "avoid_crossing_perimeters_only",
    "keep_alive_fan_speed": "fan_cooling_end_layers",
    "cool_min_feedrate": "slow_down_min_speed",
    "cool_min_layer_time": "slow_down_layer_time",
    "cool_lift_head": "lift_min_layer_time",
    "infill_hollow": "hollow_out_infill_density",
    "auto_temp_match": "auto_cooling",
    "resonance_compensation": "resonance_compensation_enabled",
    "adaptive_layer_height": "adaptive_layer_height",
    "adaptive_layer_height_variation": "adaptive_layer_height_variation",
    "adaptive_layer_height_variation_step": "adaptive_layer_height_variation_step",
    "acceleration_enabled": "acceleration_enabled",
    "acceleration_print": "acceleration_print",
    "acceleration_travel": "acceleration_travel",
    "acceleration_layer_0": "acceleration_first_layer",
    "acceleration_infill": "acceleration_infill",
    "acceleration_wall": "acceleration_perimeter",
    "acceleration_wall_0": "acceleration_prime",
    "acceleration_topbottom": "acceleration_top_bottom",
    "acceleration_support": "acceleration_support",
    "acceleration_support_interface": "acceleration_support_interface",
    "jerk_enabled": "jerk_enabled",
    "jerk_print": "jerk_print",
    "jerk_travel": "jerk_travel",
    "jerk_layer_0": "jerk_first_layer",
    "jerk_infill": "jerk_infill",
    "jerk_wall": "jerk_perimeter",
    "jerk_topbottom": "jerk_top_bottom",
    "jerk_support": "jerk_support",
    "jerk_support_interface": "jerk_support_interface",
    "support_extruder_nr": "support_extruder",
    "support_infill_extruder_nr": "support_infill_extruder",
    "support_roof_extruder_nr": "support_roof_extruder",
    "support_bottom_extruder_nr": "support_bottom_extruder",
    "support_offset": "support_offset",
    "support_roof_offset": "support_roof_offset",
    "support_bottom_offset": "support_bottom_offset",
    "support_join_distance": "support_join_distance",
    "support_pattern": "support_pattern",
    "support_roof_pattern": "support_roof_pattern",
    "support_bottom_pattern": "support_bottom_pattern",
    "support_line_width": "support_line_width",
    "support_z_distance": "support_top_distance",
    "support_xy_distance": "support_xy_distance",
    "support_xy_overrides_z": "support_xy_overrides_z",
    "support_stair_step_height": "support_critical_enabled",
    "support_top_bottom_thickness": "support_thickness",
    "support_interface_thickness": "support_interface_thickness",
    "support_interface_skip_height": "support_interface_skip_height",
    "prime_tower_enable": "prime_tower",
    "prime_tower_size": "prime_tower_size",
    "prime_tower_position": "prime_tower_position",
    "prime_tower_brim_width": "prime_tower_brim_width",
    "raft_base_thickness": "raft_base_thickness",
    "raft_interface_thickness": "raft_interface_thickness",
    "raft_surface_layers": "raft_surface_layers",
    "raft_airgap": "raft_airgap",
    "raft_first_layer_density": "raft_first_layer_density",
    "brim_width": "brim_width",
    "brim_outside_only": "brim_only_outside",
    "brim_type": "brim_type",
    "skirt_gap": "skirt_gap",
    "skirt_line_count": "skirt_line_count",
    "skirt_minimal_length": "skirt_minimal_length",
    "adhesion_type": "adhesion_type",
    "platform_surface_texture": "bed_type",
    "z_seam_corner": "seam_corner_type",
    "z_seam_x": "seam_x",
    "z_seam_y": "seam_y",
    "z_seam_type": "seam_position",
    "hole_xy_offset": "hole_offset",
    "extra_perimeter": "extra_perimeters",
    "extra_perimeter_odd_layers": "extra_perimeters_odd_layers",
    "min_feature_size": "min_bead_width",
    "min_outer_wall_flow": "min_outer_wall_bead_width",
    "min_inner_wall_flow": "min_inner_wall_bead_width",
    "inner_wall_line_width": "wall_wall_line_width",
    "inner_wall_speed": "wall_wall_speed",
    "outer_wall_line_width": "wall_outer_wall_line_width",
    "outer_wall_speed": "wall_outer_wall_speed",
    "skin_line_width": "top_bottom_top_line_width",
    "skin_speed": "top_bottom_speed",
    "infill_line_width": "infill_line_width",
    "infill_speed": "infill_speed",
    "skirt_brim_speed": "skirt_brim_speed",
    "travel_speed": "travel_speed",
    "layer_start_x": "layer_start_x",
    "layer_start_y": "layer_start_y",
    "acceleration_enabled": "acceleration_enabled",
    "acceleration_print": "acceleration_print",
    "acceleration_travel": "acceleration_travel",
    "jerk_enabled": "jerk_enabled",
    "jerk_print": "jerk_print",
    "jerk_travel": "jerk_travel",
    "flow_rate": "max_volumetric_speed",
    "wall_0_wipe_dist": "wipe_distance",
    "bridge_settings_enabled": "bridge_settings_enabled",
    "bridge_angle": "bridge_angle",
    "bridge_skin_speed": "bridge_speed",
    "bridge_fan_enabled": "bridge_fan_enabled",
    "bridge_fan_speed": "bridge_fan_speed",
    "layer_0_z_offset": "z_offset",
    "initial_layer_line_width_factor": "initial_layer_line_width",
    "initial_layer_print_speed": "initial_layer_speed",
    "min_infill_area": "min_infill_area",
    "min_skin_width_for_expansion": "min_skin_width_for_expansion",
    "sparse_infill_fan_threshold": "sparse_infill_fan_threshold",
    "sparse_infill_line_distance": "sparse_infill_line_distance",
    "sparse_infill_pattern": "sparse_infill_pattern",
    "sparse_infill_density": "fill_density",
    "sparse_infill_angles": "infill_angles",
    "infill_extruder": "infill_extruder",
    "infill_first": "infill_first",
    "cross_infill_pocket_size": "cross_infill_pocket_size",
    "alternate_extra_perimeter": "alternate_extra_perimeter",
    "uzzy_pillows_enabled": "fuzzy_skin_enabled",
    "uzzy_pillows_thickness": "fuzzy_skin_thickness",
    "uzzy_pillards_point_density": "fuzzy_skin_point_distance",
    "coasting_enable": "coasting_enable",
    "coasting_volume": "coasting_volume",
    "coasting_speed": "coasting_speed",
    "select_by_mesh": "print_selected",
    "exclude_tower": "exclude_tower",
    "cloud_api_enabled": "cloud_api_enabled",
    "cloud_sync_enabled": "cloud_sync_enabled",
    "infinite_skirt": "infinite_skirt",
    "optimize_wall_printing_order": "optimize_wall_printing_order",
}

CURA_TO_BAMBU = {
    "print_temperature": "nozzle_temperature",
    "print_temperature_layer_0": "nozzle_temperature_initial_layer",
    "bed_temperature": "bed_temperature",
    "bed_temperature_layer_0": "bed_temperature_initial_layer",
    "fan_speed": "fan_speed",
    "fan_speed_layer_0": "fan_speed_initial_layer",
    "material": "filament_type",
    "print_speed": "speed_print",
    "travel_speed": "speed_travel",
    "infill_sparse_density": "fill_density",
    "wall_thickness": "wall_loops",
    "layer_height": "layer_height",
    "bottom_layers": "bottom_shell_layers",
    "top_layers": "top_shell_layers",
    "infill_pattern": "infill_pattern",
    "wall_pattern": "wall_infill_order",
    "retraction_enable": "retract_enable",
    "retraction_speed": "retract_speed",
    "retraction_distance": "retract_length",
    "retraction_min_travel": "retract_before_travel",
    "retraction_combing": "retraction_combing",
    "skin_overlap": "overlap_ratio",
    "support_enable": "enable_support",
    "support_type": "support_type",
    "support_angle": "support_threshold_angle",
    "support_line_distance": "support_density",
    "platform_adhesion": "adhesion_type",
    "brim_width": "brim_width",
    "raft_margin": "raft_offset",
    "skirt_line_count": "skirt_line_count",
    "skirt_gap": "skirt_gap",
    "cool_fan_enabled": "fan_always_on",
    "cool_fan_speed": "fan_speed",
    "cool_fan_full_layer": "full_fan_speed_layer",
    "outer_before_inner_walls": "wall_order",
    "fill_perimeter_gaps": "fill_perimeter_gaps",
    "ironing_enabled": "ironing",
    "ironing_spacing": "ironing_spacing",
    "ironing_angle": "ironing_angle",
    "sequence": "print_sequence",
    "outer_inset_first": "outer_wall_mode",
    "z_seam_x": "seam_x",
    "z_seam_y": "seam_y",
    "z_seam_corner": "seam_corner_type",
    "skin_outer_before_walls": "outer_before_inner_walls",
    "magic_spiralize": "spiral_mode",
    "magic_mesh_surface_mode": "slice_mode",
    "fill_disconnected_areas": "infill_not_covered_by_surface",
    "travel_avoid_distance": "travel_avoid_distance",
    "pre_warm": "flush_into_wipe",
    "wall_0_wipe_dist": "wipe_distance",
    "fill_backwards": "infill_direction",
    "fill_ordered": "infill_every_layers",
    "force_travel": "avoid_crossing_perimeters",
    "cool_min_feedrate": "slow_down_min_speed",
    "cool_min_layer_time": "slow_down_layer_time",
    "cool_lift_head": "lift_min_layer_time",
    "infill_hollow": "hollow_out_infill_density",
    "auto_temp_match": "automatic_cooling",
    "acceleration_enabled": "acceleration_enabled",
    "acceleration_print": "acceleration_print",
    "acceleration_travel": "acceleration_travel",
    "acceleration_layer_0": "acceleration_first_layer",
    "acceleration_infill": "acceleration_infill",
    "acceleration_wall": "acceleration_perimeter",
    "acceleration_wall_0": "acceleration_prime",
    "acceleration_topbottom": "acceleration_top_bottom",
    "acceleration_support": "acceleration_support",
    "acceleration_support_interface": "acceleration_support_interface",
    "jerk_enabled": "jerk_enabled",
    "jerk_print": "jerk_print",
    "jerk_travel": "jerk_travel",
    "jerk_layer_0": "jerk_first_layer",
    "jerk_infill": "jerk_infill",
    "jerk_wall": "jerk_perimeter",
    "jerk_topbottom": "jerk_top_bottom",
    "jerk_support": "jerk_support",
    "jerk_support_interface": "jerk_support_interface",
    "support_extruder_nr": "support_extruder",
    "support_infill_extruder_nr": "support_infill_extruder",
    "support_roof_extruder_nr": "support_roof_extruder",
    "support_bottom_extruder_nr": "support_bottom_extruder",
    "support_offset": "support_offset",
    "support_roof_offset": "support_roof_offset",
    "support_bottom_offset": "support_bottom_offset",
    "support_join_distance": "support_join_distance",
    "support_pattern": "support_pattern",
    "support_roof_pattern": "support_roof_pattern",
    "support_bottom_pattern": "support_bottom_pattern",
    "support_line_width": "support_line_width",
    "support_z_distance": "support_top_distance",
    "support_xy_distance": "support_xy_distance",
    "support_xy_overrides_z": "support_xy_overrides_z",
    "support_stair_step_height": "support_critical_enabled",
    "support_top_bottom_thickness": "support_thickness",
    "support_interface_thickness": "support_interface_thickness",
    "prime_tower_enable": "prime_tower",
    "prime_tower_size": "prime_tower_size",
    "prime_tower_position": "prime_tower_position",
    "raft_base_thickness": "raft_base_thickness",
    "raft_interface_thickness": "raft_interface_thickness",
    "raft_surface_layers": "raft_surface_layers",
    "raft_airgap": "raft_airgap",
    "raft_first_layer_density": "raft_first_layer_density",
    "brim_width": "brim_width",
    "brim_outside_only": "brim_only_outside",
    "adhesion_type": "adhesion_type",
    "z_seam_corner": "seam_corner_type",
    "z_seam_x": "seam_x",
    "z_seam_y": "seam_y",
    "z_seam_type": "seam_position",
    "hole_xy_offset": "hole_offset",
    "extra_perimeter": "extra_perimeters",
    "extra_perimeter_odd_layers": "extra_perimeters_odd_layers",
    "inner_wall_line_width": "wall_wall_line_width",
    "inner_wall_speed": "wall_wall_speed",
    "outer_wall_line_width": "wall_outer_wall_line_width",
    "outer_wall_speed": "wall_outer_wall_speed",
    "skin_line_width": "top_bottom_top_line_width",
    "skin_speed": "top_bottom_speed",
    "infill_line_width": "infill_line_width",
    "infill_speed": "infill_speed",
    "travel_speed": "travel_speed",
    "layer_start_x": "layer_start_x",
    "layer_start_y": "layer_start_y",
    "flow_rate": "max_volumetric_speed",
    "wall_0_wipe_dist": "wipe_distance",
    "bridge_settings_enabled": "bridge_enable",
    "bridge_angle": "bridge_angle",
    "bridge_skin_speed": "bridge_speed",
    "bridge_fan_enabled": "bridge_fan_speed",
    "layer_0_z_offset": "z_offset",
    "initial_layer_line_width_factor": "initial_layer_line_width",
    "initial_layer_print_speed": "initial_layer_print_speed",
    "sparse_infill_pattern": "sparse_infill_pattern",
    "sparse_infill_density": "fill_density",
    "infill_extruder": "infill_extruder",
    "infill_first": "infill_first",
    "coasting_enable": "coasting_enable",
    "coasting_volume": "coasting_volume",
    "coasting_speed": "coasting_speed",
    "optimize_wall_printing_order": "optimize_wall_printing_order",
    "fuzzy_skin_enabled": "fuzzy_skin_enabled",
    "fuzzy_skin_thickness": "fuzzy_skin_thickness",
    "fuzzy_skin_point_distance": "fuzzy_skin_point_distance",
    "sync_area_mode": "sync_area_mode",
    "smart_fill": "smart_fill",
    "thin_wall_min_bead_width": "thin_wall_min_bead_width",
    "outer_wall_looping": "outer_wall_looping",
    "magic_spiralize": "spiral_mode",
    "z_hop": "z_hop",
    "z_hop_type": "z_hop_type",
    "z_hop_height": "z_hop_height",
    "enable_support": "support_enable",
    "support_type": "support_type",
    "support_threshold_angle": "support_threshold_angle",
    "support_density": "support_density",
    "support_top_distance": "support_top_distance",
    "support_bottom_distance": "support_bottom_distance",
    "support_xy_distance": "support_xy_distance",
    "support_wall_count": "support_wall_count",
    "support_filament": "support_filament",
    "support_infill_filament": "support_infill_filament",
    "support_roof_filament": "support_roof_filament",
    "support_bottom_filament": "support_bottom_filament",
    "enable_prime_tower": "prime_tower_enable",
    "prime_tower_filament": "prime_tower_filament",
    "prime_tower_wipe": "prime_tower_wipe",
    "prime_tower_cone": "prime_tower_cone",
    "adaptive_layer_height": "adaptive_layer_height",
    "alua_max_height": "alua_max_height",
    "alua_min_step_height": "alua_min_step_height",
    "alua_step_height": "alua_step_height",
    "independent_support_layer_temperature": "independent_support_layer_temperature",
    "support_temperature": "support_temperature",
    "first_layer_temperature": "first_layer_temperature",
    "first_layer_bed_temperature": "first_layer_bed_temperature",
    "bed_temperature_difference": "bed_temperature_difference",
    "temperature_vitrification": "temperature_vitrification",
    "slow_down_for_layer_cooling": "slow_down_for_layer_cooling",
    "slow_down_layer_time": "slow_down_layer_time",
    "slow_down_min_speed": "slow_down_min_speed",
    "enable_advanced_cooling": "enable_advanced_cooling",
    "fan_speed_warning_low": "fan_speed_warning_low",
    "fan_speed_warning_max": "fan_speed_warning_max",
    "fan_max_speed": "fan_max_speed",
    "fan_min_speed": "fan_min_speed",
    "fan_default_speed": "fan_default_speed",
    "cooling_modulefan_speed": "cooling_modulefan_speed",
    "full_fan_speed_layer": "full_fan_speed_layer",
    "fan_cooling_end_layers": "fan_cooling_end_layers",
    "fan_always_on": "fan_always_on",
    "force_cool_layer_time": "force_cool_layer_time",
    "layer_change_gcode": "layer_change_gcode",
    "time_cost": "time_cost",
    "filament_cost": "filament_cost",
    "filament_weight": "filament_weight",
    "filament_type": "filament_type",
    "filament_is_support": "filament_is_support",
    "filament_required_nozzle_temperature": "filament_required_nozzle_temperature",
    "filament_required_nozzle_temperature_range": "filament_required_nozzle_temperature_range",
    "filament_bed_temperature": "filament_bed_temperature",
    "filament_bed_temperature_range": "filament_bed_temperature_range",
    "filament_cooling_zone": "filament_cooling_zone",
    "filament_load_time": "filament_load_time",
    "filament_unload_time": "filament_unload_time",
    "filament_deretraction_speed": "filament_deretraction_speed",
    "filament_retraction_length": "filament_retraction_length",
    "filament_retraction_speed": "filament_retraction_speed",
    "filament_z_hop": "filament_z_hop",
    "filament_z_hop_types": "filament_z_hop_types",
    "filament_flush_multiplier": "filament_flush_multiplier",
    "filament_flush_without_retrace": "filament_flush_without_retrace",
    "filament_diameter": "filament_diameter",
    "filament_density": "filament_density",
    "filament_poisson_ratio": "filament_poisson_ratio",
    "filament_elastomer": "filament_elastomer",
    "filament_melt_index": "filament_melt_index",
    "filament_melt_index_melt_flow_rate": "filament_melt_index_melt_flow_rate",
    "filament_pressure_advance": "filament_pressure_advance",
    "filament_pressure_advance_smooth": "filament_pressure_advance_smooth",
    "filament_use_fast_skirt": "filament_use_fast_skirt",
    "filament_wipe": "filament_wipe",
    "filament_wipe_distance": "filament_wipe_distance",
    "filament_shrink": "filament_shrink",
    "filament_maximum_volumetric_speed": "filament_maximum_volumetric_speed",
    "filament_optimal_volumetric_speed": "filament_optimal_volumetric_speed",
    "filament_ramming_parameter": "filament_ramming_parameter",
    "filament_cooling_moves": "filament_cooling_moves",
    "filament_min_cooling_move_speed": "filament_min_cooling_move_speed",
    "filament_cooling_move_distance": "filament_cooling_move_distance",
    "filament_nozzle_temperature_initial_layer": "filament_nozzle_temperature_initial_layer",
    "filament_nozzle_temperature": "filament_nozzle_temperature",
    "filament_bed_temperature_initial_layer": "filament_bed_temperature_initial_layer",
    "filament_bed_temperature": "filament_bed_temperature",
    "filament_enforce_my_custom_gcode": "filament_enforce_my_custom_gcode",
    "filament_start_gcode": "filament_start_gcode",
    "filament_end_gcode": "filament_end_gcode",
    "filament_toolchange_gcode": "_startfilament_toolchange_start_gcode",
    "filament_toolchange_end_gcode": "filament_toolchange_end_gcode",
    "filament_advanced_parameter": "filament_advanced_parameter",
    "filament_ulti_switch_parameter": "filament_ultimaker_switch_extruder",
    "filament_bed_temperature_manager": "filament_bed_temperature_manager",
    "filament_timing_commands": "filament_timing_commands",
    "filament_loading_speed": "filament_loading_speed",
    "filament_loading_speed_start": "filament_loading_speed_start",
    "filament_loading_speed_end": "filament_loading_speed_end",
    "filament_unloading_speed": "filament_unloading_speed",
    "filament_unloading_speed_start": "filament_unloading_speed_start",
    "filament_unloading_speed_end": "filament_unloading_speed_end",
    "filament_load_restart_distance": "filament_load_restart_distance",
    "filament_unload_restart_distance": "filament_unload_restart_distance",
    "filament_drying_temperature": "filament_drying_temperature",
    "filament_drying_time": "filament_drying_time",
    "filament_description": "filament_description",
    "filament_uid": "filament_uid",
    "filament_preset_name": "filament_preset_name",
    "filament_brand": "filament_brand",
    "filament_model": "filament_model",
    "filament_notes": "filament_notes",
    "filament_has_version_id": "filament_has_version_id",
    "filament_is_default_preset": "filament_is_default_preset",
    "filament_vendor": "filament_vendor",
    "compatible_machine": "compatible_machine",
    "nozzle_volume_default": "nozzle_volume_default",
    "nozzle_volume": "nozzle_volume",
    "nozzle_volume_range": "nozzle_volume_range",
    "nozzle_cooldown": "nozzle_cooldown",
    "machine_type": "machine_type",
    "machine_name": "machine_name",
    "machine_manufacturer": "machine_manufacturer",
    "printable_area": "printable_area",
    "printable_height": "printable_height",
    "extruder_count": "extruder_count",
    "extruders": "extruders",
    "bed_type": "bed_type",
    "bed_max_temperature": "bed_max_temperature",
    "max_heated_bed_temperature": "max_heated_bed_temperature",
    "heated_bed": "heated_bed",
    "heated_build_volume": "heated_build_volume",
    "door_switch": "door_switch",
    "filament_switch": "filament_switch",
    "power_switch": "power_switch",
    "auxiliarycoolingfan": "auxiliarycoolingfan",
    "support_air_filtration": "support_air_filtration",
    "air_filtration": "air_filtration",
    "fan_speedup_time": "fan_speedup_time",
    "fan_speedup_smoothing": "fan_speedup_smoothing",
    "filter_max_rpm": "filter_max_rpm",
    "filter_rpm_curve": "filter_rpm_curve",
    "chamber_temperature": "chamber_temperature",
    "extruder_plate": "extruder_plate",
    "extruder_type": "extruder_type",
    "is_default": "is_default",
    "nozzle_hrc": "nozzle_hrc",
    "nozzle_type": "nozzle_type",
    "nozzle_volume": "nozzle_volume",
    "nozzle_diameter": "nozzle_diameter",
    "nozzle_min_tip_h": "nozzle_min_tip_h",
    "nozzle_min_volume": "nozzle_min_volume",
    "nozzle_multiplier": "nozzle_multiplier",
    "nozzle_offset_x": "nozzle_offset_x",
    "nozzle_offset_y": "nozzle_offset_y",
    "nozzle_coolingfan": "nozzle_coolingfan",
    "coolingfan_speed": "coolingfan_speed",
    "required_nozzle_HRC": "required_nozzle_HRC",
    "inherits": "inherits",
    "printer_model": "printer_model",
    "printer_technology": "printer_technology",
    "printer_variant": "printer_variant",
    "nozzle_size": "nozzle_size",
    "gcode_flavor": "gcode_flavor",
    "default_acceleration": "default_acceleration",
    "default_jerk": "default_jerk",
    "speed_equal_to_travel": "speed_equal_to_travel",
    "silent_mode": "silent_mode",
    "firmware_version": "firmware_version",
    "machine_start_gcode": "machine_start_gcode",
    "machine_end_gcode": "machine_end_gcode",
    "before_layer_change_gcode": "before_layer_change_gcode",
    "layer_change_gcode": "layer_change_gcode",
    "time_lapse_gcode": "time_lapse_gcode",
    "layer_end_gcode": "layer_end_gcode",
    "travel_avoid_distance": "travel_avoid_distance",
    "travel_avoid_type": "travel_avoid_type",
    "start_gcode_legacy": "start_gcode_legacy",
    "template_custom_gcode": "template_custom_gcode",
    "instantiate_extruder": "instantiate_extruder",
    "extruder_colour": "extruder_colour",
    "extruder_offset": "extruder_offset",
    "extruder_shared_extruder": "extruder_shared_extruder",
    "retraction_length": "retraction_length",
    "retraction_speed": "retraction_speed",
    "deretraction_speed": "deretraction_speed",
    "zhop": "zhop",
    "zhop_height": "zhop_height",
    "fan_speed": "fan_speed",
    "aux_fan": "aux_fan",
    "support_air_filtration": "support_air_filtration",
}


VALUE_TRANSFORMATIONS = {
    "prusaslicer": {
        "platform_adhesion": {
            "brim": "Brim",
            "raft": "Raft",
            "skirt": "Skirt",
            "none": "None",
        },
        "support_type": {
            "everywhere": "Normal",
            "buildplate": "On build plate only",
            "touching_buildplate": "On build plate only",
        },
        "support_pattern": {
            "grid": "Grid",
            "lines": "Lines",
            "zigzag": "Zigzag",
        },
        "infill_pattern": {
            "grid": "Grid",
            "lines": "Line",
            "zigzag": "Zigzag",
            "triangles": "Triangles",
            "cubic": "Cubic",
            "octagram": "Star",
            "concentric": "Concentric",
        },
    },
    "orca": {
        "platform_adhesion": {
            "brim": "brim",
            "raft": "raft",
            "skirt": "skirt",
            "none": "none",
        },
        "support_type": {
            "everywhere": "normal",
            "buildplate": "buildplate",
            "touching_buildplate": "buildplate",
        },
        "support_pattern": {
            "grid": "grid",
            "lines": "lines",
            "zigzag": "zigzag",
        },
        "infill_pattern": {
            "grid": "grid",
            "lines": "lines",
            "zigzag": "zigzag",
            "triangles": "triangles",
            "cubic": "cubic",
            "concentric": "concentric",
        },
    },
    "bambu": {
        "platform_adhesion": {
            "brim": "brim",
            "raft": "raft",
            "skirt": "skirt",
            "none": "none",
        },
        "support_type": {
            "everywhere": "normal",
            "buildplate": "buildplate",
            "touching_buildplate": "buildplate",
        },
        "support_pattern": {
            "grid": "grid",
            "lines": "lines",
            "zigzag": "zigzag",
        },
        "infill_pattern": {
            "grid": "grid",
            "lines": "lines",
            "zigzag": "zigzag",
            "triangles": "triangles",
            "cubic": "cubic",
            "concentric": "concentric",
        },
    },
}


def load_cura_settings(path: Path) -> dict:
    """Load Cura settings from JSON file."""
    try:
        with path.open("r", encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        print(f"[ERR] File not found: {path}", file=sys.stderr)
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"[ERR] Invalid JSON in {path}: {e}", file=sys.stderr)
        sys.exit(1)


def translate_value(value: str, setting: str, target_slicer: str) -> str:
    """Apply value transformations for specific slicer settings."""
    if target_slicer in VALUE_TRANSFORMATIONS:
        if setting in VALUE_TRANSFORMATIONS[target_slicer]:
            return VALUE_TRANSFORMATIONS[target_slicer][setting].get(value, value)
    return value


def convert_cura_to_prusaslicer(cura_settings: dict) -> dict:
    """Convert Cura settings to PrusaSlicer format."""
    ps_settings = {}
    
    for cura_key, value in cura_settings.items():
        if cura_key in CURA_TO_PRUSASLICER:
            ps_key = CURA_TO_PRUSASLICER[cura_key]
            if isinstance(value, str):
                value = translate_value(value, cura_key, "prusaslicer")
            ps_settings[ps_key] = value
    
    return ps_settings


def convert_cura_to_orca(cura_settings: dict) -> dict:
    """Convert Cura settings to OrcaSlicer format."""
    orca_settings = {}
    
    for cura_key, value in cura_settings.items():
        if cura_key in CURA_TO_ORCA:
            orca_key = CURA_TO_ORCA[cura_key]
            if isinstance(value, str):
                value = translate_value(value, cura_key, "orca")
            orca_settings[orca_key] = value
    
    return orca_settings


def convert_cura_to_bambu(cura_settings: dict) -> dict:
    """Convert Cura settings to Bambu Studio format."""
    bambu_settings = {}
    
    for cura_key, value in cura_settings.items():
        if cura_key in CURA_TO_BAMBU:
            bambu_key = CURA_TO_BAMBU[cura_key]
            if isinstance(value, str):
                value = translate_value(value, cura_key, "bambu")
            bambu_settings[bambu_key] = value
    
    return bambu_settings


CONVERTERS = {
    "prusaslicer": convert_cura_to_prusaslicer,
    "orca": convert_cura_to_orca,
    "bambu": convert_cura_to_bambu,
}


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Translate Cura slicer settings to PrusaSlicer, OrcaSlicer, and Bambu Studio formats."
    )
    parser.add_argument(
        "--input", "-i",
        type=Path,
        required=True,
        help="Input Cura settings JSON file"
    )
    parser.add_argument(
        "--output", "-o",
        choices=["prusaslicer", "orca", "bambu", "all"],
        default="all",
        help="Target slicer format (default: all)"
    )
    parser.add_argument(
        "--dir", "-d",
        type=Path,
        help="Output directory (default: stdout)"
    )
    parser.add_argument(
        "--pretty", "-p",
        action="store_true",
        help="Pretty print JSON output"
    )

    args = parser.parse_args()

    cura_settings = load_cura_settings(args.input)

    indent = 2 if args.pretty else None

    if args.output == "all":
        for slicer_name, converter in CONVERTERS.items():
            converted = converter(cura_settings)
            
            if args.dir:
                args.dir.mkdir(parents=True, exist_ok=True)
                output_path = args.dir / f"{args.input.stem}_{slicer_name}.json"
                with output_path.open("w", encoding="utf-8") as f:
                    json.dump(converted, f, indent=2)
                print(f"[OK] Saved: {output_path}")
            else:
                print(f"# {slicer_name.upper()}")
                print(json.dumps(converted, indent=indent))
                print()
    else:
        converter = CONVERTERS[args.output]
        converted = converter(cura_settings)
        
        if args.dir:
            args.dir.mkdir(parents=True, exist_ok=True)
            output_path = args.dir / f"{args.input.stem}_{args.output}.json"
            with output_path.open("w", encoding="utf-8") as f:
                json.dump(converted, f, indent=2)
            print(f"[OK] Saved: {output_path}")
        else:
            print(f"# {args.output.upper()}")
            print(json.dumps(converted, indent=indent))


if __name__ == "__main__":
    main()
