#!/usr/bin/env python3
"""
temp_tower.py

Generate a temperature tower G-code for calibrating optimal printing temperature.
The tower tests temperatures from 180°C to 260°C in configurable increments.

Usage:
    python tools/temp_tower.py filament/Hatchbox/PLA.json
    python tools/temp_tower.py filament/Generic/PETG.json --output tower.gcode
    python tools/temp_tower.py filament/Generic/PLA.json --min-temp 190 --max-temp 230 --step 5
    python tools/temp_tower.py filament/Generic/PLA.json --layers-per-temp 15
"""

import argparse
import json
import sys
from pathlib import Path
from typing import Optional


def load_filament_profile(path: Path) -> dict:
    """Load a filament profile JSON file."""
    try:
        with path.open("r", encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        print(f"[ERR] Filament profile not found: {path}", file=sys.stderr)
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"[ERR] Invalid JSON in {path}: {e}", file=sys.stderr)
        sys.exit(1)


def generate_start_gcode(
    bed_temp: float,
    initial_nozzle_temp: float,
    fan_speed: int,
    nozzle_diameter: float = 0.4
) -> str:
    """Generate start G-code for the temperature tower."""
    lines = [
        "; Temperature Tower G-code",
        "; Generated by OpenPrint3D temp_tower.py",
        "; ========================================",
        ";",
        "; This tower tests different nozzle temperatures",
        "; to help find the optimal printing temperature.",
        ";",
        "; Tower sections are printed from bottom to top.",
        "; Each section has a different temperature marked.",
        ";",
        "; ========================================",
        "",
        "G90 ; Absolute positioning",
        "M82 ; Absolute extrusion mode",
        "",
        "; Home all axes",
        "G28 ; Home all axes",
        "",
        "; Set bed temperature and wait",
        f"M140 S{bed_temp:.0f} ; Set bed temperature",
        f"M190 S{bed_temp:.0f} ; Wait for bed temperature",
        "",
        "; Set initial nozzle temperature and wait",
        f"M104 S{initial_nozzle_temp:.0f} ; Set nozzle temperature",
        f"M109 S{initial_nozzle_temp:.0f} ; Wait for nozzle temperature",
        "",
        "; Prime line",
        "G1 Z5 F3000 ; Lift nozzle",
        "G1 X10 Y10 F6000 ; Move to start position",
        "G1 Z0.3 F3000 ; Lower to first layer height",
        "G1 X200 E20 F1500 ; Prime line",
        "G1 Z2 F3000 ; Lift nozzle",
        "G1 X10 F6000 ; Move away",
        "",
        "; Set fan speed",
        f"M106 S{int(fan_speed * 255 / 100)} ; Set fan to {fan_speed}%",
        "",
        "; Start printing",
        "G92 E0 ; Reset extruder position",
        "",
    ]
    return "\n".join(lines)


def generate_tower_section(
    temp: float,
    section_height: float,
    layer_height: float,
    nozzle_diameter: float,
    layer_count: int,
    section_num: int,
    base_x: float = 50.0,
    base_y: float = 50.0,
    tower_width: float = 20.0,
    tower_depth: float = 20.0
) -> str:
    """Generate G-code for a single temperature section of the tower."""
    lines = [
        "",
        f"; ========================================",
        f"; TEMPERATURE SECTION {section_num}: {temp:.0f}°C",
        f"; ========================================",
        f"M104 S{temp:.0f} ; Set nozzle temperature to {temp:.0f}°C",
        "",
    ]
    
    e_pos = 0.0
    z_pos = section_height
    
    for layer in range(layer_count):
        z = z_pos + (layer * layer_height)
        lines.append(f"; Layer {layer + 1}/{layer_count} at Z={z:.2f}")
        lines.append(f"G1 Z{z:.2f} F3000")
        
        if layer == 0:
            lines.append(f"M109 S{temp:.0f} ; Wait for temperature change")
        
        perimeter_length = 2 * (tower_width + tower_depth)
        extrusion = perimeter_length * layer_height * nozzle_diameter / (nozzle_diameter * layer_height)
        e_pos += extrusion
        
        lines.append(f"G1 X{base_x:.1f} Y{base_y:.1f} F6000")
        lines.append(f"G1 X{base_x + tower_width:.1f} Y{base_y:.1f} E{e_pos:.3f} F1500")
        lines.append(f"G1 X{base_x + tower_width:.1f} Y{base_y + tower_depth:.1f} E{e_pos + extrusion:.3f}")
        e_pos += extrusion
        lines.append(f"G1 X{base_x:.1f} Y{base_y + tower_depth:.1f} E{e_pos + extrusion:.3f}")
        e_pos += extrusion
        lines.append(f"G1 X{base_x:.1f} Y{base_y:.1f} E{e_pos + extrusion:.3f}")
        e_pos += extrusion
        lines.append("")
    
    return "\n".join(lines)


def generate_end_gcode(
    bed_temp: float,
    park_position: tuple = (10, 10, 50)
) -> str:
    """Generate end G-code for the temperature tower."""
    lines = [
        "",
        "; ========================================",
        "; END G-CODE",
        "; ========================================",
        "",
        "; Turn off heaters",
        "M104 S0 ; Turn off nozzle heater",
        "M140 S0 ; Turn off bed heater",
        "M106 S0 ; Turn off fan",
        "",
        "; Park nozzle",
        f"G1 Z{park_position[2]:.1f} F3000 ; Lift nozzle",
        f"G1 X{park_position[0]:.1f} Y{park_position[1]:.1f} F6000 ; Park position",
        "",
        "; Disable motors",
        "M84 ; Disable motors",
        "",
        "; Print complete",
        "M73 P100 ; Print progress 100%",
        "",
        "; ========================================",
        "; TEMPERATURE TOWER COMPLETE",
        "; ========================================",
        ";",
        "; Inspect each section for:",
        ";  - Layer adhesion quality",
        ";  - Surface finish (stringing, blobs)",
        ";  - Overhang quality",
        ";  - Bridging performance",
        ";",
        "; The best overall quality indicates",
        "; your optimal printing temperature.",
        "; ========================================",
    ]
    return "\n".join(lines)


def generate_temp_label_gcode(
    temp: float,
    section_num: int,
    base_x: float = 50.0,
    base_y: float = 50.0,
    tower_width: float = 20.0,
    tower_depth: float = 20.0,
    z_height: float = 0.0,
    layer_height: float = 0.2,
    nozzle_diameter: float = 0.4
) -> str:
    """Generate G-code to emboss temperature number on the tower face."""
    lines = [
        f"; Temperature label: {temp:.0f}°C",
    ]
    return "\n".join(lines)


def generate_tower(
    filament_profile: dict,
    min_temp: float = 180.0,
    max_temp: float = 260.0,
    temp_step: float = 10.0,
    layers_per_temp: int = 15,
    layer_height: float = 0.2,
    nozzle_diameter: float = 0.4,
    tower_width: float = 20.0,
    tower_depth: float = 20.0,
    base_x: float = 50.0,
    base_y: float = 50.0
) -> str:
    """Generate complete temperature tower G-code."""
    bed_temp = filament_profile.get("bed", {}).get("recommended", 60)
    fan_speed = filament_profile.get("fan", {}).get("recommended", 100)
    
    temps = []
    current_temp = min_temp
    while current_temp <= max_temp:
        temps.append(current_temp)
        current_temp += temp_step
    
    if not temps:
        print("[ERR] No temperature levels generated. Check min/max/step values.", file=sys.stderr)
        sys.exit(1)
    
    gcode_parts = []
    
    gcode_parts.append(generate_start_gcode(
        bed_temp=bed_temp,
        initial_nozzle_temp=temps[0],
        fan_speed=fan_speed,
        nozzle_diameter=nozzle_diameter
    ))
    
    gcode_parts.append("")
    gcode_parts.append("; Tower Configuration:")
    gcode_parts.append(f";   Temperatures: {min_temp:.0f}°C to {max_temp:.0f}°C")
    gcode_parts.append(f";   Temperature step: {temp_step:.0f}°C")
    gcode_parts.append(f";   Layers per temperature: {layers_per_temp}")
    gcode_parts.append(f";   Layer height: {layer_height}mm")
    gcode_parts.append(f";   Total temperature sections: {len(temps)}")
    gcode_parts.append(f";   Estimated tower height: {len(temps) * layers_per_temp * layer_height:.1f}mm")
    gcode_parts.append(f";   Bed temperature: {bed_temp:.0f}°C")
    gcode_parts.append(f";   Fan speed: {fan_speed}%")
    gcode_parts.append("")
    
    for i, temp in enumerate(temps):
        section_height = i * layers_per_temp * layer_height
        section_gcode = generate_tower_section(
            temp=temp,
            section_height=section_height,
            layer_height=layer_height,
            nozzle_diameter=nozzle_diameter,
            layer_count=layers_per_temp,
            section_num=i + 1,
            base_x=base_x,
            base_y=base_y,
            tower_width=tower_width,
            tower_depth=tower_depth
        )
        gcode_parts.append(section_gcode)
    
    gcode_parts.append(generate_end_gcode(bed_temp=bed_temp))
    
    return "\n".join(gcode_parts)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate a temperature tower G-code for calibrating optimal printing temperature."
    )
    parser.add_argument(
        "filament_profile",
        type=Path,
        help="Path to the filament profile JSON file"
    )
    parser.add_argument(
        "--output", "-o",
        type=Path,
        help="Output G-code file path (default: stdout)"
    )
    parser.add_argument(
        "--min-temp",
        type=float,
        default=180.0,
        help="Minimum temperature to test (default: 180°C)"
    )
    parser.add_argument(
        "--max-temp",
        type=float,
        default=260.0,
        help="Maximum temperature to test (default: 260°C)"
    )
    parser.add_argument(
        "--step",
        type=float,
        default=10.0,
        help="Temperature step between sections (default: 10°C)"
    )
    parser.add_argument(
        "--layers-per-temp",
        type=int,
        default=15,
        help="Number of layers per temperature section (default: 15)"
    )
    parser.add_argument(
        "--layer-height",
        type=float,
        default=0.2,
        help="Layer height in mm (default: 0.2)"
    )
    parser.add_argument(
        "--nozzle-diameter",
        type=float,
        default=0.4,
        help="Nozzle diameter in mm (default: 0.4)"
    )
    parser.add_argument(
        "--tower-width",
        type=float,
        default=20.0,
        help="Tower width in mm (default: 20)"
    )
    parser.add_argument(
        "--tower-depth",
        type=float,
        default=20.0,
        help="Tower depth in mm (default: 20)"
    )
    parser.add_argument(
        "--base-x",
        type=float,
        default=50.0,
        help="Base X position on bed (default: 50)"
    )
    parser.add_argument(
        "--base-y",
        type=float,
        default=50.0,
        help="Base Y position on bed (default: 50)"
    )

    args = parser.parse_args()

    profile = load_filament_profile(args.filament_profile)
    
    material = profile.get("material", "Unknown")
    brand = profile.get("brand", "Unknown")
    name = profile.get("name", "Unknown")
    
    print(f"Generating temperature tower for: {brand} {name} ({material})", file=sys.stderr)

    gcode = generate_tower(
        filament_profile=profile,
        min_temp=args.min_temp,
        max_temp=args.max_temp,
        temp_step=args.step,
        layers_per_temp=args.layers_per_temp,
        layer_height=args.layer_height,
        nozzle_diameter=args.nozzle_diameter,
        tower_width=args.tower_width,
        tower_depth=args.tower_depth,
        base_x=args.base_x,
        base_y=args.base_y
    )

    if args.output:
        with args.output.open("w", encoding="utf-8") as f:
            f.write(gcode)
        print(f"G-code written to: {args.output}", file=sys.stderr)
    else:
        print(gcode)


if __name__ == "__main__":
    main()
